import { chromium } from "@playwright/test"
const EXE = `${process.env.HOME}/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell`
const browser = await chromium.launch({ executablePath: EXE, args:["--no-sandbox","--disable-gpu"] })
const ctx = await browser.newContext({ viewport:{width:1440,height:900}, locale:"zh-CN", extraHTTPHeaders:{ "X-Parsar-Dev-User-ID": process.env.DEV_USER } })
await ctx.addInitScript((ws)=>{localStorage.setItem("parsar.theme","light");localStorage.setItem("parsar.lang","zh-CN");localStorage.setItem("parsar.ws",ws)},process.env.WS)
const page = await ctx.newPage()
page.on("response", r => { if (r.url().includes("/api/") && (r.status()>=400 || r.request().method()!=="GET")) console.log(" ", r.status(), r.request().method(), r.url().split("/api/v1")[1]) })
page.on("pageerror", e => console.log("  PAGEERROR", e.message.slice(0,160)))
await page.goto("http://127.0.0.1:5173/?admin=agents",{waitUntil:"load"}); await page.waitForTimeout(2500)
const row = page.locator('[role="option"]').first()
await row.hover(); await page.waitForTimeout(400)
console.log("clicking 聊一下 …")
await row.getByRole("button", { name: "聊一下" }).click()
await page.waitForTimeout(4000)
console.log("url:", page.url())
await page.screenshot({ path: ".impeccable/review/crawl/agents-chat.png" })
const body = (await page.locator("main").innerText()).split("\n").slice(0,6).join(" / ")
console.log("main text:", body.slice(0,200))
await browser.close()
