package deepseekharness

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/MiniMax-AI-Dev/parsar/apps/parsar-daemon/internal/enginehost"
	"gopkg.in/yaml.v3"
)

// The resident-server profile. dsh ships profiles for a desktop app and
// for one-shot headless runs; neither fits a daemon that wants the /api
// gateway and nothing else, so Parsar generates its own.
//
// The row set below is minimal in the literal sense: each row was added
// because booting without it failed, and the profile is a plain
// dsh-base bundle plus these rows — no browser roster, no frontend
// assets, no telemetry surface.
const (
	// serverProfileName is the generated profile's directory name under
	// $DSH_HOME/profiles.
	serverProfileName = "parsar-api"

	// baseBundle is the shipped plugin bundle the profile builds on.
	baseBundle = "@deepseek-ai/dsh-base"

	// apiPathPrefix is where the carrier mounts the gateway.
	apiPathPrefix = "/api"

	// eventsMuxPath is the multiplexed session event downlink. It is a
	// WebSocket upgrade, not an SSE stream: a plain GET answers 426.
	eventsMuxPath = apiPathPrefix + "/events.mux"
)

// insertRow is a profile patch entry that adds plugin rows rather than
// replacing an existing row's config.
type insertRow struct {
	Insert []pluginRow `yaml:"insert"`
}

type pluginRow struct {
	ID     string `yaml:"id"`
	Name   string `yaml:"name"`
	Config any    `yaml:"config,omitempty"`
}

type storageJSONConfig struct {
	// Root is a plain absolute path. dsh's own profiles write this as a
	// `!!js dshHomePath(...)` expression; Parsar knows the home it just
	// created, so a literal path keeps the generated file free of dsh's
	// script tag.
	Root string `yaml:"root"`
}

type storageDomainConfig struct {
	Backend string `yaml:"backend"`
}

type apiGatewayConfig struct {
	// NativeOpen stays false: the daemon has no desktop session to open
	// a path into, and leaving it on would let a turn ask the host to
	// launch an application.
	NativeOpen bool `yaml:"nativeOpen"`
}

type webServerConfig struct {
	Host string `yaml:"host"`
	Port int    `yaml:"port"`
}

type clientConnectionConfig struct {
	// TrustedHosts stays empty so the gateway's trust fence accepts only
	// loopback callers. Adding an entry here would expose an
	// unauthenticated agent runtime to that host.
	TrustedHosts []string `yaml:"trustedHosts"`
}

// serverProfileSpec is what the profile needs to be materialised.
type serverProfileSpec struct {
	Home     string
	Port     int
	Provider providerConfig
	// HasProvider mirrors normaliseProvider's second return: false means
	// no Parsar-managed route, so dsh resolves its own credentials.
	HasProvider bool
	Model       string
	ProviderID  string
}

// writeServerProfile materialises $DSH_HOME/profiles/<serverProfileName>
// for one launch of the resident server.
//
// Writing into the profile directory (rather than $DSH_HOME's own
// cordis.patch.yml) is deliberate: dsh watches the home layer for live
// edits, so a home-level patch would be re-applied to an already-running
// server. The profile layer is read once at boot, and only the
// supervisor writes it — one launch per state key at a time.
func writeServerProfile(spec serverProfileSpec) error {
	dir := filepath.Join(spec.Home, "profiles", serverProfileName)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("deepseekharness: mkdir server profile %s: %w", dir, err)
	}

	manifest, err := json.MarshalIndent(map[string]any{
		"name":    "dsh-profile-" + serverProfileName,
		"private": true,
		"dsh":     map[string]any{"profile": map[string]any{"bundles": []string{baseBundle}}},
	}, "", "  ")
	if err != nil {
		return fmt.Errorf("deepseekharness: marshal server profile manifest: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "package.json"), append(manifest, '\n'), 0o600); err != nil {
		return fmt.Errorf("deepseekharness: write server profile manifest: %w", err)
	}

	// The profile root is an empty entry list on purpose: the tree is
	// composed from the bundle plus cordis.patch.yml, which is the only
	// file Parsar has to reason about.
	root := "# Generated by parsar-daemon. The tree is composed from the bundle in\n" +
		"# package.json plus cordis.patch.yml; edit neither by hand.\n[]\n"
	if err := os.WriteFile(filepath.Join(dir, "cordis.yml"), []byte(root), 0o600); err != nil {
		return fmt.Errorf("deepseekharness: write server profile root: %w", err)
	}

	body, err := renderServerPatch(spec)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "cordis.patch.yml"), body, 0o600); err != nil {
		return fmt.Errorf("deepseekharness: write server profile patch: %w", err)
	}
	return nil
}

// renderServerPatch builds the profile's patch layer: the shared override
// rows, then the plugin rows dsh-base leaves out.
func renderServerPatch(spec serverProfileSpec) ([]byte, error) {
	overrides, err := overrideRows(spec.Provider, spec.HasProvider, spec.Model, spec.ProviderID)
	if err != nil {
		return nil, err
	}

	rows := make([]any, 0, len(overrides)+1)
	for _, row := range overrides {
		rows = append(rows, row)
	}
	rows = append(rows, insertRow{Insert: []pluginRow{
		// Storage: the session log's backing store. storage-domain needs
		// an explicit backend or the tree fails config validation.
		{ID: "storage", Name: "@deepseek-ai/dsh-storage"},
		{ID: "storage-json", Name: "@deepseek-ai/dsh-storage-json",
			Config: storageJSONConfig{Root: filepath.Join(spec.Home, "storages")}},
		{ID: "storage-domain", Name: "@deepseek-ai/dsh-storage-domain",
			Config: storageDomainConfig{Backend: "json"}},

		// The gateway resolves sessions through the workspace registry,
		// and its directory picker must be the non-interactive variant:
		// the daemon has no human to answer a native dialog.
		{ID: "workspace", Name: "@deepseek-ai/dsh-workspace"},
		{ID: "directory-picker", Name: "@deepseek-ai/dsh-host-directory-picker-auto"},

		// The gateway itself. It registers no HTTP routes — it only
		// provides ctx.apiProxy.
		{ID: "api-gateway", Name: "@deepseek-ai/dsh-host-apiproxy",
			Config: apiGatewayConfig{NativeOpen: false}},

		// The physical carrier. Without this row the gateway exists but
		// every /api path answers 404, because the transport is what
		// mounts the prefix and the events.mux upgrade.
		{ID: "webserver", Name: "@deepseek-ai/dsh-host-webserver",
			Config: webServerConfig{Host: enginehost.LoopbackHost, Port: spec.Port}},
		{ID: "client-connection", Name: "@deepseek-ai/dsh-client-connection",
			Config: clientConnectionConfig{TrustedHosts: []string{}}},
	}})

	body, err := yaml.Marshal(rows)
	if err != nil {
		return nil, fmt.Errorf("deepseekharness: marshal server profile patch: %w", err)
	}
	header := "# Generated by parsar-daemon for the resident dsh /api server.\n"
	return append([]byte(header), body...), nil
}
