// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, tenant_id, metadata, configuration)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, metadata, configuration, created_at, updated_at
`

type CreateAgentParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Metadata      []byte      `json:"metadata"`
	Configuration []byte      `json:"configuration"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.TenantID,
		arg.Metadata,
		arg.Configuration,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Metadata,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, tenant_id, metadata, configuration, created_at, updated_at FROM agents WHERE tenant_id = $1 AND id = $2
`

type GetAgentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.TenantID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Metadata,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
