// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironmentTemplate = `-- name: CreateEnvironmentTemplate :one
INSERT INTO environment_templates (id, tenant_id, name, network_access)
VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, name, network_access, created_at, updated_at
`

type CreateEnvironmentTemplateParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Name          pgtype.Text `json:"name"`
	NetworkAccess string      `json:"network_access"`
}

func (q *Queries) CreateEnvironmentTemplate(ctx context.Context, arg CreateEnvironmentTemplateParams) (EnvironmentTemplate, error) {
	row := q.db.QueryRow(ctx, createEnvironmentTemplate,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.NetworkAccess,
	)
	var i EnvironmentTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NetworkAccess,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironmentTemplate = `-- name: DeleteEnvironmentTemplate :one
DELETE FROM environment_templates WHERE tenant_id = $1 AND id = $2 RETURNING id
`

type DeleteEnvironmentTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteEnvironmentTemplate(ctx context.Context, arg DeleteEnvironmentTemplateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEnvironmentTemplate, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEnvironmentTemplate = `-- name: GetEnvironmentTemplate :one
SELECT id, tenant_id, name, network_access, created_at, updated_at FROM environment_templates WHERE tenant_id = $1 AND id = $2
`

type GetEnvironmentTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetEnvironmentTemplate(ctx context.Context, arg GetEnvironmentTemplateParams) (EnvironmentTemplate, error) {
	row := q.db.QueryRow(ctx, getEnvironmentTemplate, arg.TenantID, arg.ID)
	var i EnvironmentTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NetworkAccess,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironmentTemplates = `-- name: ListEnvironmentTemplates :many
SELECT id, tenant_id, name, network_access, created_at, updated_at FROM environment_templates
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL
       OR (NOT $3::boolean AND (created_at, id) < ($2::timestamptz, $4::uuid))
       OR ($3::boolean AND (created_at, id) > ($2::timestamptz, $4::uuid)))
ORDER BY
    CASE WHEN $3::boolean THEN created_at END ASC,
    CASE WHEN $3::boolean THEN id END ASC,
    CASE WHEN NOT $3::boolean THEN created_at END DESC,
    CASE WHEN NOT $3::boolean THEN id END DESC
LIMIT $5
`

type ListEnvironmentTemplatesParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	Ascending    bool               `json:"ascending"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageLimit    int32              `json:"page_limit"`
}

func (q *Queries) ListEnvironmentTemplates(ctx context.Context, arg ListEnvironmentTemplatesParams) ([]EnvironmentTemplate, error) {
	rows, err := q.db.Query(ctx, listEnvironmentTemplates,
		arg.TenantID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentTemplate{}
	for rows.Next() {
		var i EnvironmentTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NetworkAccess,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentTemplate = `-- name: UpdateEnvironmentTemplate :one
UPDATE environment_templates SET
    name = CASE WHEN $1::boolean THEN $2::text ELSE name END,
    network_access = CASE WHEN $3::boolean THEN $4::text ELSE network_access END,
    updated_at = clock_timestamp()
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, name, network_access, created_at, updated_at
`

type UpdateEnvironmentTemplateParams struct {
	SetName       bool        `json:"set_name"`
	Name          pgtype.Text `json:"name"`
	SetNetwork    bool        `json:"set_network"`
	NetworkAccess string      `json:"network_access"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateEnvironmentTemplate(ctx context.Context, arg UpdateEnvironmentTemplateParams) (EnvironmentTemplate, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentTemplate,
		arg.SetName,
		arg.Name,
		arg.SetNetwork,
		arg.NetworkAccess,
		arg.TenantID,
		arg.ID,
	)
	var i EnvironmentTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NetworkAccess,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
