// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_executor_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateEnvironmentExecutor = `-- name: AuthenticateEnvironmentExecutor :one
SELECT s.tenant_id
FROM environment_executor_credentials c
JOIN environments e ON e.id = c.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE c.environment_id = $1 AND c.token_sha256 = $2
    AND c.revoked_at IS NULL AND s.deleted_at IS NULL
`

type AuthenticateEnvironmentExecutorParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TokenSha256   string      `json:"token_sha256"`
}

func (q *Queries) AuthenticateEnvironmentExecutor(ctx context.Context, arg AuthenticateEnvironmentExecutorParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, authenticateEnvironmentExecutor, arg.EnvironmentID, arg.TokenSha256)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const issueEnvironmentExecutorCredential = `-- name: IssueEnvironmentExecutorCredential :execrows
INSERT INTO environment_executor_credentials (environment_id, token_sha256)
VALUES ($1, $2) ON CONFLICT (environment_id) DO NOTHING
`

type IssueEnvironmentExecutorCredentialParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TokenSha256   string      `json:"token_sha256"`
}

func (q *Queries) IssueEnvironmentExecutorCredential(ctx context.Context, arg IssueEnvironmentExecutorCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, issueEnvironmentExecutorCredential, arg.EnvironmentID, arg.TokenSha256)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeEnvironmentExecutorCredential = `-- name: RevokeEnvironmentExecutorCredential :execrows
UPDATE environment_executor_credentials SET revoked_at = COALESCE(revoked_at, clock_timestamp())
WHERE environment_id = $1
`

func (q *Queries) RevokeEnvironmentExecutorCredential(ctx context.Context, environmentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeEnvironmentExecutorCredential, environmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateEnvironmentExecutorCredential = `-- name: RotateEnvironmentExecutorCredential :execrows
UPDATE environment_executor_credentials
SET token_sha256 = $2, issued_at = clock_timestamp(), revoked_at = NULL
WHERE environment_id = $1
`

type RotateEnvironmentExecutorCredentialParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TokenSha256   string      `json:"token_sha256"`
}

func (q *Queries) RotateEnvironmentExecutorCredential(ctx context.Context, arg RotateEnvironmentExecutorCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateEnvironmentExecutorCredential, arg.EnvironmentID, arg.TokenSha256)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
