// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Engine         string             `json:"engine"`
	Metadata       []byte             `json:"metadata"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Configuration  []byte             `json:"configuration"`
}

type Turn struct {
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
	Outcome           []byte             `json:"outcome"`
}

type TurnInput struct {
	Sequence       int64              `json:"sequence"`
	SessionID      pgtype.UUID        `json:"session_id"`
	TurnID         pgtype.UUID        `json:"turn_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	BatchPosition  int32              `json:"batch_position"`
}
