// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Name           string             `json:"name"`
	CredentialHash string             `json:"credential_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type FunctionCall struct {
	SessionID      pgtype.UUID        `json:"session_id"`
	TurnID         pgtype.UUID        `json:"turn_id"`
	CallID         string             `json:"call_id"`
	ExecutorCallID string             `json:"executor_call_id"`
	Name           string             `json:"name"`
	Arguments      []byte             `json:"arguments"`
	Result         []byte             `json:"result"`
	Applied        bool               `json:"applied"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Engine         string             `json:"engine"`
	Metadata       []byte             `json:"metadata"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Configuration  []byte             `json:"configuration"`
	EventSequence  int64              `json:"event_sequence"`
}

type SessionDevice struct {
	SessionID       pgtype.UUID `json:"session_id"`
	DeviceID        pgtype.UUID `json:"device_id"`
	NativeSessionID string      `json:"native_session_id"`
}

type SessionEvent struct {
	SessionID    pgtype.UUID `json:"session_id"`
	Sequence     int64       `json:"sequence"`
	Payload      []byte      `json:"payload"`
	PayloadBytes pgtype.Int4 `json:"payload_bytes"`
}

type SessionItem struct {
	ID          pgtype.UUID        `json:"id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	TurnID      pgtype.UUID        `json:"turn_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Position    int32              `json:"position"`
	Payload     []byte             `json:"payload"`
	OutputIndex pgtype.Int4        `json:"output_index"`
}

type Turn struct {
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
	Outcome           []byte             `json:"outcome"`
	EventCount        int32              `json:"event_count"`
	EventBytes        int64              `json:"event_bytes"`
	TokenUsage        []byte             `json:"token_usage"`
}

type TurnEvent struct {
	SessionID pgtype.UUID        `json:"session_id"`
	TurnID    pgtype.UUID        `json:"turn_id"`
	Ordinal   int32              `json:"ordinal"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TurnInput struct {
	Sequence       int64              `json:"sequence"`
	SessionID      pgtype.UUID        `json:"session_id"`
	TurnID         pgtype.UUID        `json:"turn_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	BatchPosition  int32              `json:"batch_position"`
}
