// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Engine         string             `json:"engine"`
	Metadata       []byte             `json:"metadata"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Configuration  []byte             `json:"configuration"`
}
