// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, tenant_id, engine, metadata, idempotency_key, request_hash, configuration)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, idempotency_key) DO UPDATE
SET idempotency_key = EXCLUDED.idempotency_key
WHERE sessions.request_hash = EXCLUDED.request_hash
RETURNING id, tenant_id, engine, metadata, idempotency_key, request_hash, created_at, configuration, event_sequence
`

type CreateSessionParams struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	Engine         string      `json:"engine"`
	Metadata       []byte      `json:"metadata"`
	IdempotencyKey string      `json:"idempotency_key"`
	RequestHash    string      `json:"request_hash"`
	Configuration  []byte      `json:"configuration"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.TenantID,
		arg.Engine,
		arg.Metadata,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.Configuration,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Engine,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.Configuration,
		&i.EventSequence,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, tenant_id, engine, metadata, idempotency_key, request_hash, created_at, configuration, event_sequence FROM sessions WHERE tenant_id = $1 AND id = $2
`

type GetSessionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.TenantID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Engine,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.Configuration,
		&i.EventSequence,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, tenant_id, engine, metadata, idempotency_key, request_hash, created_at, configuration, event_sequence FROM sessions
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL
       OR (NOT $3::boolean AND (created_at, id) < ($2::timestamptz, $4::uuid))
       OR ($3::boolean AND (created_at, id) > ($2::timestamptz, $4::uuid)))
ORDER BY
    CASE WHEN $3::boolean THEN created_at END ASC,
    CASE WHEN $3::boolean THEN id END ASC,
    CASE WHEN NOT $3::boolean THEN created_at END DESC,
    CASE WHEN NOT $3::boolean THEN id END DESC
LIMIT $5
`

type ListSessionsParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	Ascending    bool               `json:"ascending"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageLimit    int32              `json:"page_limit"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.TenantID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Engine,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.CreatedAt,
			&i.Configuration,
			&i.EventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionMetadata = `-- name: UpdateSessionMetadata :one
UPDATE sessions SET metadata = $3 WHERE tenant_id = $1 AND id = $2 RETURNING id, tenant_id, engine, metadata, idempotency_key, request_hash, created_at, configuration, event_sequence
`

type UpdateSessionMetadataParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) UpdateSessionMetadata(ctx context.Context, arg UpdateSessionMetadataParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionMetadata, arg.TenantID, arg.ID, arg.Metadata)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Engine,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.Configuration,
		&i.EventSequence,
	)
	return i, err
}
