// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionItem = `-- name: GetSessionItem :one
SELECT id, session_id, turn_id, created_at, position, payload, output_index FROM session_items WHERE session_id = $1 AND id = $2
`

type GetSessionItemParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetSessionItem(ctx context.Context, arg GetSessionItemParams) (SessionItem, error) {
	row := q.db.QueryRow(ctx, getSessionItem, arg.SessionID, arg.ID)
	var i SessionItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.CreatedAt,
		&i.Position,
		&i.Payload,
		&i.OutputIndex,
	)
	return i, err
}

const hasNativeMessageItem = `-- name: HasNativeMessageItem :one
SELECT EXISTS(SELECT 1 FROM session_items WHERE turn_id = $1
    AND payload->>'role' = 'assistant' AND id <> $2)
`

type HasNativeMessageItemParams struct {
	TurnID pgtype.UUID `json:"turn_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) HasNativeMessageItem(ctx context.Context, arg HasNativeMessageItemParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasNativeMessageItem, arg.TurnID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const itemEventSources = `-- name: ItemEventSources :many
SELECT session_id, turn_id, ordinal, kind, payload, created_at FROM turn_events WHERE session_id = $1 AND turn_id = $2 AND ordinal >= $3 ORDER BY ordinal
`

type ItemEventSourcesParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	Ordinal   int32       `json:"ordinal"`
}

func (q *Queries) ItemEventSources(ctx context.Context, arg ItemEventSourcesParams) ([]TurnEvent, error) {
	rows, err := q.db.Query(ctx, itemEventSources, arg.SessionID, arg.TurnID, arg.Ordinal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TurnEvent{}
	for rows.Next() {
		var i TurnEvent
		if err := rows.Scan(
			&i.SessionID,
			&i.TurnID,
			&i.Ordinal,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itemInputSource = `-- name: ItemInputSource :one
SELECT sequence, session_id, turn_id, idempotency_key, kind, payload, created_at, batch_position FROM turn_inputs WHERE session_id = $1 AND sequence = $2
`

type ItemInputSourceParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Sequence  int64       `json:"sequence"`
}

func (q *Queries) ItemInputSource(ctx context.Context, arg ItemInputSourceParams) (TurnInput, error) {
	row := q.db.QueryRow(ctx, itemInputSource, arg.SessionID, arg.Sequence)
	var i TurnInput
	err := row.Scan(
		&i.Sequence,
		&i.SessionID,
		&i.TurnID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
		&i.BatchPosition,
	)
	return i, err
}

const itemSources = `-- name: ItemSources :many
SELECT kind, payload, created_at, source_order, source_type FROM (
    SELECT kind, payload, created_at, sequence AS source_order, 0::integer AS source_type
    FROM turn_inputs inp WHERE inp.session_id = $1 AND inp.turn_id = $2 AND kind = 'message'
    UNION ALL
    SELECT kind, payload, created_at, ordinal::bigint AS source_order, 1::integer AS source_type
    FROM turn_events evt WHERE evt.session_id = $1 AND evt.turn_id = $2
) AS sources
WHERE ($3::timestamptz IS NULL
    OR (created_at, source_type, source_order) > ($3::timestamptz, $4::integer, $5::bigint))
ORDER BY created_at, source_type, source_order LIMIT 100
`

type ItemSourcesParams struct {
	SessionID    pgtype.UUID        `json:"session_id"`
	TurnID       pgtype.UUID        `json:"turn_id"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	AfterType    int32              `json:"after_type"`
	AfterOrder   int64              `json:"after_order"`
}

type ItemSourcesRow struct {
	Kind        string             `json:"kind"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SourceOrder int64              `json:"source_order"`
	SourceType  int32              `json:"source_type"`
}

func (q *Queries) ItemSources(ctx context.Context, arg ItemSourcesParams) ([]ItemSourcesRow, error) {
	rows, err := q.db.Query(ctx, itemSources,
		arg.SessionID,
		arg.TurnID,
		arg.AfterCreated,
		arg.AfterType,
		arg.AfterOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemSourcesRow{}
	for rows.Next() {
		var i ItemSourcesRow
		if err := rows.Scan(
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.SourceOrder,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionItems = `-- name: ListSessionItems :many
SELECT i.id, i.created_at,
    (CASE WHEN i.payload->>'status' = 'in_progress' AND t.status IN ('completed', 'failed', 'cancelled')
         THEN jsonb_set(i.payload, '{status}', '"incomplete"') ELSE i.payload END)::jsonb AS payload
FROM session_items i JOIN turns t ON t.id = i.turn_id
WHERE i.session_id = $1
  AND ($2::timestamptz IS NULL
       OR ($3::boolean AND (i.created_at, i.position, i.id) > ($2::timestamptz, $4::integer, $5::uuid))
       OR (NOT $3::boolean AND (i.created_at, i.position, i.id) < ($2::timestamptz, $4::integer, $5::uuid)))
ORDER BY
    CASE WHEN $3::boolean THEN i.created_at END ASC,
    CASE WHEN $3::boolean THEN i.position END ASC,
    CASE WHEN $3::boolean THEN i.id END ASC,
    CASE WHEN NOT $3::boolean THEN i.created_at END DESC,
    CASE WHEN NOT $3::boolean THEN i.position END DESC,
    CASE WHEN NOT $3::boolean THEN i.id END DESC
LIMIT $6
`

type ListSessionItemsParams struct {
	SessionID     pgtype.UUID        `json:"session_id"`
	AfterCreated  pgtype.Timestamptz `json:"after_created"`
	Ascending     bool               `json:"ascending"`
	AfterPosition int32              `json:"after_position"`
	AfterID       pgtype.UUID        `json:"after_id"`
	PageLimit     int32              `json:"page_limit"`
}

type ListSessionItemsRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Payload   []byte             `json:"payload"`
}

func (q *Queries) ListSessionItems(ctx context.Context, arg ListSessionItemsParams) ([]ListSessionItemsRow, error) {
	rows, err := q.db.Query(ctx, listSessionItems,
		arg.SessionID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterPosition,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionItemsRow{}
	for rows.Next() {
		var i ListSessionItemsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markItemsIndexed = `-- name: MarkItemsIndexed :exec
UPDATE turns SET items_indexed = true WHERE session_id = $1 AND id = $2
`

type MarkItemsIndexedParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) MarkItemsIndexed(ctx context.Context, arg MarkItemsIndexedParams) error {
	_, err := q.db.Exec(ctx, markItemsIndexed, arg.SessionID, arg.ID)
	return err
}

const putSessionItem = `-- name: PutSessionItem :exec
INSERT INTO session_items(id, session_id, turn_id, created_at, payload, position, output_index)
VALUES ($1, $2, $3, $4, $5,
    (SELECT COALESCE(max(position), -1) + 1 FROM session_items WHERE session_id = $2),
    CASE WHEN $6::boolean THEN
        (SELECT COALESCE(max(output_index), -1) + 1 FROM session_items WHERE turn_id = $3)
    END)
ON CONFLICT (id) DO UPDATE SET payload = EXCLUDED.payload
`

type PutSessionItemParams struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	TurnID    pgtype.UUID        `json:"turn_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Payload   []byte             `json:"payload"`
	IsOutput  bool               `json:"is_output"`
}

func (q *Queries) PutSessionItem(ctx context.Context, arg PutSessionItemParams) error {
	_, err := q.db.Exec(ctx, putSessionItem,
		arg.ID,
		arg.SessionID,
		arg.TurnID,
		arg.CreatedAt,
		arg.Payload,
		arg.IsOutput,
	)
	return err
}

const unindexedItemTurn = `-- name: UnindexedItemTurn :one
SELECT id, session_id, status, created_at, started_at, completed_at, cancel_requested_at, outcome, event_count, event_bytes, items_indexed, token_usage FROM turns WHERE session_id = $1 AND NOT items_indexed ORDER BY created_at, id LIMIT 1
`

func (q *Queries) UnindexedItemTurn(ctx context.Context, sessionID pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, unindexedItemTurn, sessionID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.Outcome,
		&i.EventCount,
		&i.EventBytes,
		&i.ItemsIndexed,
		&i.TokenUsage,
	)
	return i, err
}
