// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: token_usage.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const putTurnUsage = `-- name: PutTurnUsage :exec
UPDATE turns SET token_usage = $3 WHERE session_id = $1 AND id = $2
`

type PutTurnUsageParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	ID         pgtype.UUID `json:"id"`
	TokenUsage []byte      `json:"token_usage"`
}

func (q *Queries) PutTurnUsage(ctx context.Context, arg PutTurnUsageParams) error {
	_, err := q.db.Exec(ctx, putTurnUsage, arg.SessionID, arg.ID, arg.TokenUsage)
	return err
}

const sessionTokenUsage = `-- name: SessionTokenUsage :one
SELECT CASE WHEN count(token_usage) = 0 THEN NULL ELSE jsonb_build_object(
 'input_tokens', sum((token_usage->>'input_tokens')::numeric),
 'input_tokens_details', jsonb_build_object('cached_tokens', sum((token_usage->'input_tokens_details'->>'cached_tokens')::numeric)),
 'output_tokens', sum((token_usage->>'output_tokens')::numeric),
 'output_tokens_details', jsonb_build_object('reasoning_tokens', sum((token_usage->'output_tokens_details'->>'reasoning_tokens')::numeric)),
 'total_tokens', sum((token_usage->>'total_tokens')::numeric)
) END::jsonb AS usage
FROM turns WHERE session_id = $1
`

func (q *Queries) SessionTokenUsage(ctx context.Context, sessionID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, sessionTokenUsage, sessionID)
	var usage []byte
	err := row.Scan(&usage)
	return usage, err
}
