// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vault_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaticCredential = `-- name: CreateStaticCredential :one
INSERT INTO vault_credentials (id, vault_id, name, auth_type, mcp_server_url, token_ciphertext)
SELECT $1, v.id, $2, 'static_bearer', $3, $4
FROM vaults v
WHERE v.tenant_id = $5 AND v.id = $6
RETURNING id, vault_id, name, auth_type, mcp_server_url, created_at, updated_at
`

type CreateStaticCredentialParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	McpServerUrl    string      `json:"mcp_server_url"`
	TokenCiphertext []byte      `json:"token_ciphertext"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	VaultID         pgtype.UUID `json:"vault_id"`
}

type CreateStaticCredentialRow struct {
	ID           pgtype.UUID        `json:"id"`
	VaultID      pgtype.UUID        `json:"vault_id"`
	Name         string             `json:"name"`
	AuthType     string             `json:"auth_type"`
	McpServerUrl string             `json:"mcp_server_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStaticCredential(ctx context.Context, arg CreateStaticCredentialParams) (CreateStaticCredentialRow, error) {
	row := q.db.QueryRow(ctx, createStaticCredential,
		arg.ID,
		arg.Name,
		arg.McpServerUrl,
		arg.TokenCiphertext,
		arg.TenantID,
		arg.VaultID,
	)
	var i CreateStaticCredentialRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredential = `-- name: GetCredential :one
SELECT c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.created_at, c.updated_at
FROM vault_credentials c
JOIN vaults v ON v.id = c.vault_id
WHERE v.tenant_id = $1 AND v.id = $2 AND c.id = $3
`

type GetCredentialParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	VaultID  pgtype.UUID `json:"vault_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetCredentialRow struct {
	ID           pgtype.UUID        `json:"id"`
	VaultID      pgtype.UUID        `json:"vault_id"`
	Name         string             `json:"name"`
	AuthType     string             `json:"auth_type"`
	McpServerUrl string             `json:"mcp_server_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (GetCredentialRow, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.TenantID, arg.VaultID, arg.ID)
	var i GetCredentialRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStaticCredential = `-- name: UpdateStaticCredential :one
UPDATE vault_credentials c
SET token_ciphertext = $1, updated_at = statement_timestamp()
FROM vaults v
WHERE v.id = c.vault_id AND v.tenant_id = $2
  AND v.id = $3 AND c.id = $4
  AND c.auth_type = 'static_bearer' AND c.mcp_server_url = $5
RETURNING c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.created_at, c.updated_at
`

type UpdateStaticCredentialParams struct {
	TokenCiphertext []byte      `json:"token_ciphertext"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	VaultID         pgtype.UUID `json:"vault_id"`
	ID              pgtype.UUID `json:"id"`
	McpServerUrl    string      `json:"mcp_server_url"`
}

type UpdateStaticCredentialRow struct {
	ID           pgtype.UUID        `json:"id"`
	VaultID      pgtype.UUID        `json:"vault_id"`
	Name         string             `json:"name"`
	AuthType     string             `json:"auth_type"`
	McpServerUrl string             `json:"mcp_server_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateStaticCredential(ctx context.Context, arg UpdateStaticCredentialParams) (UpdateStaticCredentialRow, error) {
	row := q.db.QueryRow(ctx, updateStaticCredential,
		arg.TokenCiphertext,
		arg.TenantID,
		arg.VaultID,
		arg.ID,
		arg.McpServerUrl,
	)
	var i UpdateStaticCredentialRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
