// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vaults.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVault = `-- name: CreateVault :one
INSERT INTO vaults (id, tenant_id, name, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, metadata, created_at
`

type CreateVaultParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     pgtype.Text `json:"name"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateVault(ctx context.Context, arg CreateVaultParams) (Vault, error) {
	row := q.db.QueryRow(ctx, createVault,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Metadata,
	)
	var i Vault
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getVault = `-- name: GetVault :one
SELECT id, tenant_id, name, metadata, created_at FROM vaults WHERE tenant_id = $1 AND id = $2
`

type GetVaultParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetVault(ctx context.Context, arg GetVaultParams) (Vault, error) {
	row := q.db.QueryRow(ctx, getVault, arg.TenantID, arg.ID)
	var i Vault
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
