#!/usr/bin/env bash
set -euo pipefail

PARSAR_HOME="${PARSAR_HOME:-$HOME/.parsar}"
cat <<PATHS
PARSAR_HOME=$PARSAR_HOME
PARSAR_CONFIG_DIR=$PARSAR_HOME/config
PARSAR_LOG_DIR=$PARSAR_HOME/logs
PARSAR_STATE_DIR=$PARSAR_HOME/state
PARSAR_CACHE_DIR=$PARSAR_HOME/cache
PARSAR_DEV_DIR=$PARSAR_HOME/dev
PATHS
