// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_run_retry.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentRunRetry = `-- name: CreateAgentRunRetry :exec
insert into agent_runs (
  id, workspace_id, conversation_id, agent_id, connector_type,
  trigger_message_id, trigger_source, trigger_channel, trigger_ref_type, trigger_ref_id,
  requested_by_type, requested_by_id, status, visibility, metadata, created_at, updated_at
) values (
  $1::uuid, $2::uuid, $3::uuid, $4::uuid, $5,
  $6::uuid, 'manual', 'web', 'agent_run', $7::uuid,
  'user', $8::uuid, 'queued', $9, $10::jsonb, $11, $11
)
`

type CreateAgentRunRetryParams struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ConversationID   pgtype.UUID        `json:"conversation_id"`
	AgentID          pgtype.UUID        `json:"agent_id"`
	ConnectorType    string             `json:"connector_type"`
	TriggerMessageID pgtype.UUID        `json:"trigger_message_id"`
	RetryOfRunID     pgtype.UUID        `json:"retry_of_run_id"`
	RequestedByID    pgtype.UUID        `json:"requested_by_id"`
	Visibility       string             `json:"visibility"`
	Metadata         []byte             `json:"metadata"`
	Now              pgtype.Timestamptz `json:"now"`
}

func (q *Queries) CreateAgentRunRetry(ctx context.Context, arg CreateAgentRunRetryParams) error {
	_, err := q.db.Exec(ctx, createAgentRunRetry,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.AgentID,
		arg.ConnectorType,
		arg.TriggerMessageID,
		arg.RetryOfRunID,
		arg.RequestedByID,
		arg.Visibility,
		arg.Metadata,
		arg.Now,
	)
	return err
}

const getAgentRunRetrySource = `-- name: GetAgentRunRetrySource :one
select r.workspace_id::text as workspace_id, r.conversation_id::text as conversation_id,
       r.agent_id::text as agent_id, r.trigger_message_id, r.visibility,
       a.connector_type, coalesce(r.metadata->>'retry_run_id', '')::text as retry_run_id
from agent_runs r
join agents a on a.id = r.agent_id and a.workspace_id = r.workspace_id
join conversations c on c.id = r.conversation_id and c.workspace_id = r.workspace_id
join workspaces w on w.id = r.workspace_id
join messages m on m.id = r.trigger_message_id
  and m.workspace_id = r.workspace_id and m.conversation_id = r.conversation_id
where r.id = $1::uuid
  and r.status in ('failed', 'cancelled', 'interrupted')
  and a.status = 'active' and a.deleted_at is null
  and c.status = 'active' and c.deleted_at is null
  and w.deleted_at is null and m.deleted_at is null
for update of r
`

type GetAgentRunRetrySourceRow struct {
	WorkspaceID      string      `json:"workspace_id"`
	ConversationID   string      `json:"conversation_id"`
	AgentID          string      `json:"agent_id"`
	TriggerMessageID pgtype.UUID `json:"trigger_message_id"`
	Visibility       string      `json:"visibility"`
	ConnectorType    string      `json:"connector_type"`
	RetryRunID       string      `json:"retry_run_id"`
}

func (q *Queries) GetAgentRunRetrySource(ctx context.Context, id pgtype.UUID) (GetAgentRunRetrySourceRow, error) {
	row := q.db.QueryRow(ctx, getAgentRunRetrySource, id)
	var i GetAgentRunRetrySourceRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ConversationID,
		&i.AgentID,
		&i.TriggerMessageID,
		&i.Visibility,
		&i.ConnectorType,
		&i.RetryRunID,
	)
	return i, err
}
