// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agentdaemon.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAgentDaemonDeviceOwner = `-- name: ClaimAgentDaemonDeviceOwner :one

insert into agent_daemon_device_owners (
  device_id, workspace_id, owner_pod_id, owner_url, generation,
  status, connected_at, last_seen_at, lease_expires_at, updated_at
)
values (
  $1::uuid, $2::uuid, $3::text, $4::text, 1,
  'connected', $5, $5, $6, $5
)
on conflict (device_id) do update
set workspace_id = excluded.workspace_id,
    owner_pod_id = excluded.owner_pod_id,
    owner_url = excluded.owner_url,
    generation = agent_daemon_device_owners.generation + 1,
    status = 'connected',
    connected_at = excluded.connected_at,
    last_seen_at = excluded.last_seen_at,
    lease_expires_at = excluded.lease_expires_at,
    updated_at = excluded.updated_at
returning device_id::text, workspace_id::text, owner_pod_id, owner_url,
  generation, status, connected_at, last_seen_at, lease_expires_at, updated_at
`

type ClaimAgentDaemonDeviceOwnerParams struct {
	DeviceID       pgtype.UUID        `json:"device_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	OwnerPodID     string             `json:"owner_pod_id"`
	OwnerUrl       string             `json:"owner_url"`
	Now            pgtype.Timestamptz `json:"now"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

type ClaimAgentDaemonDeviceOwnerRow struct {
	DeviceID       string             `json:"device_id"`
	WorkspaceID    string             `json:"workspace_id"`
	OwnerPodID     string             `json:"owner_pod_id"`
	OwnerUrl       string             `json:"owner_url"`
	Generation     int64              `json:"generation"`
	Status         string             `json:"status"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// agentdaemon.sql — multi-pod WebSocket owner leases for agent_daemon.
// Latest successful WebSocket dial-in wins and receives a fresh generation.
// Older sessions can still exist briefly, but renew/release operations are
// fenced by generation so they cannot affect the new owner row.
func (q *Queries) ClaimAgentDaemonDeviceOwner(ctx context.Context, arg ClaimAgentDaemonDeviceOwnerParams) (ClaimAgentDaemonDeviceOwnerRow, error) {
	row := q.db.QueryRow(ctx, claimAgentDaemonDeviceOwner,
		arg.DeviceID,
		arg.WorkspaceID,
		arg.OwnerPodID,
		arg.OwnerUrl,
		arg.Now,
		arg.LeaseExpiresAt,
	)
	var i ClaimAgentDaemonDeviceOwnerRow
	err := row.Scan(
		&i.DeviceID,
		&i.WorkspaceID,
		&i.OwnerPodID,
		&i.OwnerUrl,
		&i.Generation,
		&i.Status,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.LeaseExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireAgentDaemonDeviceOwners = `-- name: ExpireAgentDaemonDeviceOwners :execrows
update agent_daemon_device_owners
set status = 'expired',
    updated_at = $1
where lease_expires_at < $1
  and status <> 'expired'
`

func (q *Queries) ExpireAgentDaemonDeviceOwners(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, expireAgentDaemonDeviceOwners, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentDaemonDeviceOwner = `-- name: GetAgentDaemonDeviceOwner :one
select device_id::text, workspace_id::text, owner_pod_id, owner_url,
  generation, status, connected_at, last_seen_at, lease_expires_at, updated_at
from agent_daemon_device_owners
where device_id = $1::uuid
`

type GetAgentDaemonDeviceOwnerRow struct {
	DeviceID       string             `json:"device_id"`
	WorkspaceID    string             `json:"workspace_id"`
	OwnerPodID     string             `json:"owner_pod_id"`
	OwnerUrl       string             `json:"owner_url"`
	Generation     int64              `json:"generation"`
	Status         string             `json:"status"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAgentDaemonDeviceOwner(ctx context.Context, deviceID pgtype.UUID) (GetAgentDaemonDeviceOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAgentDaemonDeviceOwner, deviceID)
	var i GetAgentDaemonDeviceOwnerRow
	err := row.Scan(
		&i.DeviceID,
		&i.WorkspaceID,
		&i.OwnerPodID,
		&i.OwnerUrl,
		&i.Generation,
		&i.Status,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.LeaseExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseAgentDaemonDeviceOwner = `-- name: ReleaseAgentDaemonDeviceOwner :execrows
delete from agent_daemon_device_owners
where device_id = $1::uuid
  and owner_pod_id = $2::text
  and generation = $3::bigint
`

type ReleaseAgentDaemonDeviceOwnerParams struct {
	DeviceID   pgtype.UUID `json:"device_id"`
	OwnerPodID string      `json:"owner_pod_id"`
	Generation int64       `json:"generation"`
}

func (q *Queries) ReleaseAgentDaemonDeviceOwner(ctx context.Context, arg ReleaseAgentDaemonDeviceOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseAgentDaemonDeviceOwner, arg.DeviceID, arg.OwnerPodID, arg.Generation)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewAgentDaemonDeviceOwner = `-- name: RenewAgentDaemonDeviceOwner :one
update agent_daemon_device_owners
set last_seen_at = $1,
    lease_expires_at = $2,
    status = 'connected',
    updated_at = $1
where device_id = $3::uuid
  and owner_pod_id = $4::text
  and generation = $5::bigint
returning device_id::text, workspace_id::text, owner_pod_id, owner_url,
  generation, status, connected_at, last_seen_at, lease_expires_at, updated_at
`

type RenewAgentDaemonDeviceOwnerParams struct {
	Now            pgtype.Timestamptz `json:"now"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	DeviceID       pgtype.UUID        `json:"device_id"`
	OwnerPodID     string             `json:"owner_pod_id"`
	Generation     int64              `json:"generation"`
}

type RenewAgentDaemonDeviceOwnerRow struct {
	DeviceID       string             `json:"device_id"`
	WorkspaceID    string             `json:"workspace_id"`
	OwnerPodID     string             `json:"owner_pod_id"`
	OwnerUrl       string             `json:"owner_url"`
	Generation     int64              `json:"generation"`
	Status         string             `json:"status"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RenewAgentDaemonDeviceOwner(ctx context.Context, arg RenewAgentDaemonDeviceOwnerParams) (RenewAgentDaemonDeviceOwnerRow, error) {
	row := q.db.QueryRow(ctx, renewAgentDaemonDeviceOwner,
		arg.Now,
		arg.LeaseExpiresAt,
		arg.DeviceID,
		arg.OwnerPodID,
		arg.Generation,
	)
	var i RenewAgentDaemonDeviceOwnerRow
	err := row.Scan(
		&i.DeviceID,
		&i.WorkspaceID,
		&i.OwnerPodID,
		&i.OwnerUrl,
		&i.Generation,
		&i.Status,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.LeaseExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}
