// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_mcp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgentMCPToken = `-- name: DeleteAgentMCPToken :exec
DELETE FROM agent_mcp_tokens WHERE agent_id = $1 AND user_id = $2
`

type DeleteAgentMCPTokenParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAgentMCPToken(ctx context.Context, arg DeleteAgentMCPTokenParams) error {
	_, err := q.db.Exec(ctx, deleteAgentMCPToken, arg.AgentID, arg.UserID)
	return err
}

const getAgentMCPToken = `-- name: GetAgentMCPToken :one
SELECT created_at, expires_at FROM agent_mcp_tokens
WHERE agent_id = $1 AND user_id = $2
`

type GetAgentMCPTokenParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

type GetAgentMCPTokenRow struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetAgentMCPToken(ctx context.Context, arg GetAgentMCPTokenParams) (GetAgentMCPTokenRow, error) {
	row := q.db.QueryRow(ctx, getAgentMCPToken, arg.AgentID, arg.UserID)
	var i GetAgentMCPTokenRow
	err := row.Scan(&i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const putAgentMCPToken = `-- name: PutAgentMCPToken :exec
INSERT INTO agent_mcp_tokens (agent_id, user_id, token_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (agent_id, user_id) DO UPDATE
SET token_hash = EXCLUDED.token_hash, created_at = EXCLUDED.created_at,
    expires_at = EXCLUDED.expires_at
`

type PutAgentMCPTokenParams struct {
	AgentID   pgtype.UUID        `json:"agent_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) PutAgentMCPToken(ctx context.Context, arg PutAgentMCPTokenParams) error {
	_, err := q.db.Exec(ctx, putAgentMCPToken,
		arg.AgentID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const resolveAgentMCPToken = `-- name: ResolveAgentMCPToken :one
SELECT t.agent_id::text, t.user_id::text, a.workspace_id::text, a.name, a.description
FROM agent_mcp_tokens t
JOIN agents a ON a.id = t.agent_id AND a.deleted_at IS NULL AND a.status = 'active'
JOIN workspaces w ON w.id = a.workspace_id AND w.deleted_at IS NULL
JOIN users u ON u.id = t.user_id AND u.deleted_at IS NULL AND u.status = 'active'
JOIN workspace_members m ON m.workspace_id = a.workspace_id AND m.user_id = t.user_id
  AND m.deleted_at IS NULL AND m.status = 'active' AND m.role IN ('owner', 'admin', 'member')
WHERE t.token_hash = $1 AND t.expires_at > $2
`

type ResolveAgentMCPTokenParams struct {
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type ResolveAgentMCPTokenRow struct {
	TAgentID     string `json:"t_agent_id"`
	TUserID      string `json:"t_user_id"`
	AWorkspaceID string `json:"a_workspace_id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
}

func (q *Queries) ResolveAgentMCPToken(ctx context.Context, arg ResolveAgentMCPTokenParams) (ResolveAgentMCPTokenRow, error) {
	row := q.db.QueryRow(ctx, resolveAgentMCPToken, arg.TokenHash, arg.ExpiresAt)
	var i ResolveAgentMCPTokenRow
	err := row.Scan(
		&i.TAgentID,
		&i.TUserID,
		&i.AWorkspaceID,
		&i.Name,
		&i.Description,
	)
	return i, err
}
