// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditRecord = `-- name: GetAuditRecord :one
select id, occurred_at, source, event_type, actor_type, actor_id,
       target_type, target_id, workspace_id, payload
from audit_records
where id = $1::bigint
`

type GetAuditRecordRow struct {
	ID          int64              `json:"id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Source      string             `json:"source"`
	EventType   string             `json:"event_type"`
	ActorType   string             `json:"actor_type"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	TargetType  string             `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Payload     []byte             `json:"payload"`
}

func (q *Queries) GetAuditRecord(ctx context.Context, id int64) (GetAuditRecordRow, error) {
	row := q.db.QueryRow(ctx, getAuditRecord, id)
	var i GetAuditRecordRow
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.Source,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.TargetType,
		&i.TargetID,
		&i.WorkspaceID,
		&i.Payload,
	)
	return i, err
}

const insertAuditRecord = `-- name: InsertAuditRecord :exec

insert into audit_records (
  occurred_at, source, event_type, actor_type, actor_id,
  target_type, target_id, workspace_id, payload
)
values (
  $1, $2, $3, $4, $5::uuid,
  $6, $7::uuid, $8::uuid, $9::jsonb
)
`

type InsertAuditRecordParams struct {
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Source      string             `json:"source"`
	EventType   string             `json:"event_type"`
	ActorType   string             `json:"actor_type"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	TargetType  string             `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Payload     []byte             `json:"payload"`
}

// Audit records queries.
// Unified ingest + listing for admin / runtime / approval / identity / data
// audit events. Single-table design with jsonb payload (see migration
// 000005_audit_records.sql for rationale).
func (q *Queries) InsertAuditRecord(ctx context.Context, arg InsertAuditRecordParams) error {
	_, err := q.db.Exec(ctx, insertAuditRecord,
		arg.OccurredAt,
		arg.Source,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.TargetType,
		arg.TargetID,
		arg.WorkspaceID,
		arg.Payload,
	)
	return err
}

const listAuditRecords = `-- name: ListAuditRecords :many
select id, occurred_at, source, event_type, actor_type, actor_id,
       target_type, target_id, workspace_id, payload
from audit_records
where ($1::uuid is null or workspace_id = $1::uuid)
  and ($2::text = '' or source = $2::text)
  and ($3::text = '' or event_type = $3::text)
  and ($4::uuid is null or actor_id = $4::uuid)
  and ($5::text = '' or target_type = $5::text)
  and ($6::uuid is null or target_id = $6::uuid)
  and ($7::timestamptz is null or occurred_at >= $7::timestamptz)
  and ($8::timestamptz is null or occurred_at <= $8::timestamptz)
order by occurred_at desc, id desc
limit $9::int
`

type ListAuditRecordsParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Source      string             `json:"source"`
	EventType   string             `json:"event_type"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	TargetType  string             `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
	ItemLimit   int32              `json:"item_limit"`
}

type ListAuditRecordsRow struct {
	ID          int64              `json:"id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Source      string             `json:"source"`
	EventType   string             `json:"event_type"`
	ActorType   string             `json:"actor_type"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	TargetType  string             `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Payload     []byte             `json:"payload"`
}

// Generic filter list. Pass empty/null for any filter you want to skip.
// workspace_id / actor_id / target_id are pgtype.UUID — pass
// {Valid:false} to skip. source / event_type / target_type are text — pass
// empty string to skip. since / until are pgtype.Timestamptz — pass
// {Valid:false} to skip.
func (q *Queries) ListAuditRecords(ctx context.Context, arg ListAuditRecordsParams) ([]ListAuditRecordsRow, error) {
	rows, err := q.db.Query(ctx, listAuditRecords,
		arg.WorkspaceID,
		arg.Source,
		arg.EventType,
		arg.ActorID,
		arg.TargetType,
		arg.TargetID,
		arg.Since,
		arg.Until,
		arg.ItemLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRecordsRow{}
	for rows.Next() {
		var i ListAuditRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Source,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.TargetType,
			&i.TargetID,
			&i.WorkspaceID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
