// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blob.sql

package sqlc

import (
	"context"
)

const deleteCapabilityBlob = `-- name: DeleteCapabilityBlob :exec
delete from capability_blob
where storage_ref = $1::text
`

// Cleanup hook for capability deletion. Idempotent.
func (q *Queries) DeleteCapabilityBlob(ctx context.Context, storageRef string) error {
	_, err := q.db.Exec(ctx, deleteCapabilityBlob, storageRef)
	return err
}

const getCapabilityBlobBytes = `-- name: GetCapabilityBlobBytes :one
select bytes
from capability_blob
where storage_ref = $1::text
`

// Hot download path: the proxy GET streams these bytes back.
func (q *Queries) GetCapabilityBlobBytes(ctx context.Context, storageRef string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCapabilityBlobBytes, storageRef)
	var bytes []byte
	err := row.Scan(&bytes)
	return bytes, err
}

const getCapabilityBlobMeta = `-- name: GetCapabilityBlobMeta :one
select sha256, size_bytes, workspace_id
from capability_blob
where storage_ref = $1::text
`

type GetCapabilityBlobMetaRow struct {
	Sha256      string `json:"sha256"`
	SizeBytes   int64  `json:"size_bytes"`
	WorkspaceID string `json:"workspace_id"`
}

// Stat + cross-tenant gate: workspace_id backs BelongsToWorkspace,
// size_bytes/sha256 back Stat without pulling the full bytea.
func (q *Queries) GetCapabilityBlobMeta(ctx context.Context, storageRef string) (GetCapabilityBlobMetaRow, error) {
	row := q.db.QueryRow(ctx, getCapabilityBlobMeta, storageRef)
	var i GetCapabilityBlobMetaRow
	err := row.Scan(&i.Sha256, &i.SizeBytes, &i.WorkspaceID)
	return i, err
}

const insertCapabilityBlob = `-- name: InsertCapabilityBlob :exec

insert into capability_blob (
  storage_ref, workspace_id, bytes, sha256, size_bytes
)
values (
  $1::text, $2::text, $3::bytea,
  $4::text, $5::bigint
)
on conflict (storage_ref) do update set
  bytes        = excluded.bytes,
  sha256       = excluded.sha256,
  size_bytes   = excluded.size_bytes,
  workspace_id = excluded.workspace_id
`

type InsertCapabilityBlobParams struct {
	StorageRef  string `json:"storage_ref"`
	WorkspaceID string `json:"workspace_id"`
	Bytes       []byte `json:"bytes"`
	Sha256      string `json:"sha256"`
	SizeBytes   int64  `json:"size_bytes"`
}

// blob.sql — capability plugin/skill zip storage for the Postgres
// blob backend (migration 000003, PARSAR_BLOB_BACKEND=pg).
//
// Conventions match the rest of this dir:
//   - @param::type cast on every parameter
//   - storage_ref is the opaque reference also held in
//     capability_version.oss_key; for the PG backend it looks like
//     "pg:<uuid>". The OSS backend never touches this table.
//   - The 64 MiB cap and sha256 are enforced in the Go blob layer
//     (PGStore.PutBytes), not in SQL — see internal/storage/blob.
//
// Upsert so a re-upload of the same storage_ref overwrites cleanly.
// workspace_id is part of the update set so a corrected owner on
// re-upload is reflected (the auth gate reads it back via meta).
func (q *Queries) InsertCapabilityBlob(ctx context.Context, arg InsertCapabilityBlobParams) error {
	_, err := q.db.Exec(ctx, insertCapabilityBlob,
		arg.StorageRef,
		arg.WorkspaceID,
		arg.Bytes,
		arg.Sha256,
		arg.SizeBytes,
	)
	return err
}
