// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: capability_authoring.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockAuthoringSkill = `-- name: LockAuthoringSkill :one
select id::text
from capability
where id = $1::uuid and workspace_id = $2::uuid
  and type = 'skill' and visibility = 'workspace' and deleted_at is null
for update
`

type LockAuthoringSkillParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) LockAuthoringSkill(ctx context.Context, arg LockAuthoringSkillParams) (string, error) {
	row := q.db.QueryRow(ctx, lockAuthoringSkill, arg.ID, arg.WorkspaceID)
	var id string
	err := row.Scan(&id)
	return id, err
}
