// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: core_execution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindProductCoreSession = `-- name: BindProductCoreSession :one
UPDATE product_core_sessions SET core_session_id = $1
WHERE id = $2::uuid AND (core_session_id = '' OR core_session_id = $1)
RETURNING id, workspace_id, conversation_id, agent_id, request, core_session_id, created_at
`

type BindProductCoreSessionParams struct {
	CoreSessionID string      `json:"core_session_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) BindProductCoreSession(ctx context.Context, arg BindProductCoreSessionParams) (ProductCoreSession, error) {
	row := q.db.QueryRow(ctx, bindProductCoreSession, arg.CoreSessionID, arg.ID)
	var i ProductCoreSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.AgentID,
		&i.Request,
		&i.CoreSessionID,
		&i.CreatedAt,
	)
	return i, err
}

const bindProductCoreTurn = `-- name: BindProductCoreTurn :one
UPDATE product_core_runs SET core_turn_id = $1
WHERE run_id = $2::uuid AND (core_turn_id = '' OR core_turn_id = $1)
RETURNING run_id, session_binding_id, input, previous_turn_id, core_turn_id, submitted, attempted, settled, created_at
`

type BindProductCoreTurnParams struct {
	CoreTurnID string      `json:"core_turn_id"`
	RunID      pgtype.UUID `json:"run_id"`
}

func (q *Queries) BindProductCoreTurn(ctx context.Context, arg BindProductCoreTurnParams) (ProductCoreRun, error) {
	row := q.db.QueryRow(ctx, bindProductCoreTurn, arg.CoreTurnID, arg.RunID)
	var i ProductCoreRun
	err := row.Scan(
		&i.RunID,
		&i.SessionBindingID,
		&i.Input,
		&i.PreviousTurnID,
		&i.CoreTurnID,
		&i.Submitted,
		&i.Attempted,
		&i.Settled,
		&i.CreatedAt,
	)
	return i, err
}

const ensureProductCoreRun = `-- name: EnsureProductCoreRun :one
INSERT INTO product_core_runs (run_id, session_binding_id, input)
VALUES ($1::uuid, $2::uuid, $3::jsonb)
ON CONFLICT (run_id) DO UPDATE SET run_id = product_core_runs.run_id
RETURNING run_id, session_binding_id, input, previous_turn_id, core_turn_id, submitted, attempted, settled, created_at
`

type EnsureProductCoreRunParams struct {
	RunID            pgtype.UUID `json:"run_id"`
	SessionBindingID pgtype.UUID `json:"session_binding_id"`
	Input            []byte      `json:"input"`
}

func (q *Queries) EnsureProductCoreRun(ctx context.Context, arg EnsureProductCoreRunParams) (ProductCoreRun, error) {
	row := q.db.QueryRow(ctx, ensureProductCoreRun, arg.RunID, arg.SessionBindingID, arg.Input)
	var i ProductCoreRun
	err := row.Scan(
		&i.RunID,
		&i.SessionBindingID,
		&i.Input,
		&i.PreviousTurnID,
		&i.CoreTurnID,
		&i.Submitted,
		&i.Attempted,
		&i.Settled,
		&i.CreatedAt,
	)
	return i, err
}

const ensureProductCoreSession = `-- name: EnsureProductCoreSession :one
INSERT INTO product_core_sessions (id, workspace_id, conversation_id, agent_id, request)
SELECT $1::uuid, r.workspace_id, r.conversation_id, r.agent_id, $2::jsonb
FROM agent_runs r WHERE r.id = $3::uuid
ON CONFLICT (conversation_id, agent_id) DO UPDATE SET id = product_core_sessions.id
RETURNING id, workspace_id, conversation_id, agent_id, request, core_session_id, created_at
`

type EnsureProductCoreSessionParams struct {
	ID      pgtype.UUID `json:"id"`
	Request []byte      `json:"request"`
	RunID   pgtype.UUID `json:"run_id"`
}

func (q *Queries) EnsureProductCoreSession(ctx context.Context, arg EnsureProductCoreSessionParams) (ProductCoreSession, error) {
	row := q.db.QueryRow(ctx, ensureProductCoreSession, arg.ID, arg.Request, arg.RunID)
	var i ProductCoreSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.AgentID,
		&i.Request,
		&i.CoreSessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getProductCoreExecutionStatus = `-- name: GetProductCoreExecutionStatus :one
SELECT status FROM agent_runs WHERE id = $1::uuid AND connector_type = 'agents_api'
`

// Internal execution cleanup remains reachable after product history is hidden.
func (q *Queries) GetProductCoreExecutionStatus(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getProductCoreExecutionStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getProductCoreRunBinding = `-- name: GetProductCoreRunBinding :one
SELECT r.run_id, r.session_binding_id, r.input, r.previous_turn_id, r.core_turn_id, r.submitted, r.attempted, r.settled, r.created_at, s.core_session_id, s.workspace_id, s.conversation_id, s.agent_id
FROM product_core_runs r JOIN product_core_sessions s ON s.id = r.session_binding_id
WHERE r.run_id = $1::uuid
`

type GetProductCoreRunBindingRow struct {
	RunID            pgtype.UUID        `json:"run_id"`
	SessionBindingID pgtype.UUID        `json:"session_binding_id"`
	Input            []byte             `json:"input"`
	PreviousTurnID   pgtype.Text        `json:"previous_turn_id"`
	CoreTurnID       string             `json:"core_turn_id"`
	Submitted        bool               `json:"submitted"`
	Attempted        bool               `json:"attempted"`
	Settled          bool               `json:"settled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CoreSessionID    string             `json:"core_session_id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ConversationID   pgtype.UUID        `json:"conversation_id"`
	AgentID          pgtype.UUID        `json:"agent_id"`
}

func (q *Queries) GetProductCoreRunBinding(ctx context.Context, runID pgtype.UUID) (GetProductCoreRunBindingRow, error) {
	row := q.db.QueryRow(ctx, getProductCoreRunBinding, runID)
	var i GetProductCoreRunBindingRow
	err := row.Scan(
		&i.RunID,
		&i.SessionBindingID,
		&i.Input,
		&i.PreviousTurnID,
		&i.CoreTurnID,
		&i.Submitted,
		&i.Attempted,
		&i.Settled,
		&i.CreatedAt,
		&i.CoreSessionID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.AgentID,
	)
	return i, err
}

const listRecoverableProductCoreRuns = `-- name: ListRecoverableProductCoreRuns :many
SELECT r.id::text AS id, r.conversation_id::text AS conversation_id, r.status
FROM agent_runs r
LEFT JOIN product_core_runs cr ON cr.run_id = r.id
WHERE r.connector_type = 'agents_api' AND
  (r.status IN ('queued', 'running') OR (r.status IN ('cancelled', 'failed', 'completed') AND cr.settled = false))
ORDER BY r.created_at, r.id
`

type ListRecoverableProductCoreRunsRow struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	Status         string `json:"status"`
}

func (q *Queries) ListRecoverableProductCoreRuns(ctx context.Context) ([]ListRecoverableProductCoreRunsRow, error) {
	rows, err := q.db.Query(ctx, listRecoverableProductCoreRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecoverableProductCoreRunsRow{}
	for rows.Next() {
		var i ListRecoverableProductCoreRunsRow
		if err := rows.Scan(&i.ID, &i.ConversationID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProductCoreRun = `-- name: LockProductCoreRun :one
SELECT pg_try_advisory_xact_lock(hashtextextended(r.conversation_id::text || ':' || r.agent_id::text, 71825))::boolean
FROM agent_runs r WHERE r.id = $1::uuid
`

func (q *Queries) LockProductCoreRun(ctx context.Context, runID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, lockProductCoreRun, runID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const markProductCoreRunAttempted = `-- name: MarkProductCoreRunAttempted :exec
UPDATE product_core_runs SET attempted = true WHERE run_id = $1::uuid
`

func (q *Queries) MarkProductCoreRunAttempted(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markProductCoreRunAttempted, runID)
	return err
}

const markProductCoreRunSubmitted = `-- name: MarkProductCoreRunSubmitted :exec
UPDATE product_core_runs SET submitted = true WHERE run_id = $1::uuid
`

func (q *Queries) MarkProductCoreRunSubmitted(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markProductCoreRunSubmitted, runID)
	return err
}

const productCoreRunHasPredecessor = `-- name: ProductCoreRunHasPredecessor :one
SELECT EXISTS (
  SELECT 1 FROM agent_runs older
  LEFT JOIN product_core_runs cr ON cr.run_id = older.id
  JOIN agent_runs target ON target.id = $1::uuid
  WHERE older.conversation_id = target.conversation_id AND older.agent_id = target.agent_id
    AND (older.created_at, older.id) < (target.created_at, target.id)
    AND (older.status IN ('queued', 'running') OR (older.status IN ('cancelled', 'failed', 'completed') AND cr.settled = false))
)::boolean
`

func (q *Queries) ProductCoreRunHasPredecessor(ctx context.Context, runID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, productCoreRunHasPredecessor, runID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setProductCoreRunBaseline = `-- name: SetProductCoreRunBaseline :one
UPDATE product_core_runs SET previous_turn_id = COALESCE(previous_turn_id, $1::text)
WHERE run_id = $2::uuid RETURNING run_id, session_binding_id, input, previous_turn_id, core_turn_id, submitted, attempted, settled, created_at
`

type SetProductCoreRunBaselineParams struct {
	PreviousTurnID string      `json:"previous_turn_id"`
	RunID          pgtype.UUID `json:"run_id"`
}

func (q *Queries) SetProductCoreRunBaseline(ctx context.Context, arg SetProductCoreRunBaselineParams) (ProductCoreRun, error) {
	row := q.db.QueryRow(ctx, setProductCoreRunBaseline, arg.PreviousTurnID, arg.RunID)
	var i ProductCoreRun
	err := row.Scan(
		&i.RunID,
		&i.SessionBindingID,
		&i.Input,
		&i.PreviousTurnID,
		&i.CoreTurnID,
		&i.Submitted,
		&i.Attempted,
		&i.Settled,
		&i.CreatedAt,
	)
	return i, err
}

const settleProductCoreRun = `-- name: SettleProductCoreRun :exec
UPDATE product_core_runs SET settled = true WHERE run_id = $1::uuid
`

func (q *Queries) SettleProductCoreRun(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, settleProductCoreRun, runID)
	return err
}
