// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential_kinds.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialKind = `-- name: CreateCredentialKind :one
insert into credential_kinds(
  id, code, display_name, description,
  value_schema, built_in, source, created_by, created_at, updated_at
)
values (
  $1::uuid, $2, $3, $4,
  $5::jsonb, false, $6, $7::uuid, $8, $8
)
returning id::text as id,
          code,
          display_name,
          description,
          value_schema,
          built_in,
          source,
          coalesce(created_by::text, '') as created_by,
          created_at,
          updated_at
`

type CreateCredentialKindParams struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	ValueSchema []byte             `json:"value_schema"`
	Source      string             `json:"source"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	Now         pgtype.Timestamptz `json:"now"`
}

type CreateCredentialKindRow struct {
	ID          string             `json:"id"`
	Code        string             `json:"code"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	ValueSchema []byte             `json:"value_schema"`
	BuiltIn     bool               `json:"built_in"`
	Source      string             `json:"source"`
	CreatedBy   interface{}        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCredentialKind(ctx context.Context, arg CreateCredentialKindParams) (CreateCredentialKindRow, error) {
	row := q.db.QueryRow(ctx, createCredentialKind,
		arg.ID,
		arg.Code,
		arg.DisplayName,
		arg.Description,
		arg.ValueSchema,
		arg.Source,
		arg.CreatedBy,
		arg.Now,
	)
	var i CreateCredentialKindRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.Description,
		&i.ValueSchema,
		&i.BuiltIn,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialKindByCode = `-- name: GetCredentialKindByCode :one
select id::text as id,
       code,
       display_name,
       description,
       value_schema,
       built_in,
       source,
       coalesce(created_by::text, '') as created_by,
       created_at,
       updated_at
from credential_kinds
where code = $1
  and deleted_at is null
`

type GetCredentialKindByCodeRow struct {
	ID          string             `json:"id"`
	Code        string             `json:"code"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	ValueSchema []byte             `json:"value_schema"`
	BuiltIn     bool               `json:"built_in"`
	Source      string             `json:"source"`
	CreatedBy   interface{}        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCredentialKindByCode(ctx context.Context, code string) (GetCredentialKindByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCredentialKindByCode, code)
	var i GetCredentialKindByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.Description,
		&i.ValueSchema,
		&i.BuiltIn,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentialKinds = `-- name: ListCredentialKinds :many

select id::text as id,
       code,
       display_name,
       description,
       value_schema,
       built_in,
       source,
       coalesce(created_by::text, '') as created_by,
       created_at,
       updated_at
from credential_kinds
where deleted_at is null
order by built_in desc, code asc
`

type ListCredentialKindsRow struct {
	ID          string             `json:"id"`
	Code        string             `json:"code"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	ValueSchema []byte             `json:"value_schema"`
	BuiltIn     bool               `json:"built_in"`
	Source      string             `json:"source"`
	CreatedBy   interface{}        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Queries for credential_kinds (see migrations/000003_capability_canonical.sql
// and migrations/000004_drop_credential_kind_ui_columns.sql).
//
// Built-in kinds (built_in=TRUE) are seeded by the migration and immutable —
// the import UI should hide delete/edit affordances for them. User-created
// kinds (built_in=FALSE) carry `created_by` and can be soft-deleted.
//
// created_by is wrapped in coalesce so seed rows (where created_by IS NULL)
// scan into a non-nullable Go string; callers treat "" as "system-owned".
func (q *Queries) ListCredentialKinds(ctx context.Context) ([]ListCredentialKindsRow, error) {
	rows, err := q.db.Query(ctx, listCredentialKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialKindsRow{}
	for rows.Next() {
		var i ListCredentialKindsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DisplayName,
			&i.Description,
			&i.ValueSchema,
			&i.BuiltIn,
			&i.Source,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
