// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMemory = `-- name: GetMemory :one
select
  id::text           as id,
  scope,
  user_id::text      as user_id,
  project_id,
  memory_type,
  title,
  body,
  why,
  tags,
  source,
  agent_actor,
  conversation_id,
  created_at,
  updated_at
from memories
where id         = $1::uuid
  and deleted_at is null
`

type GetMemoryRow struct {
	ID             string             `json:"id"`
	Scope          string             `json:"scope"`
	UserID         string             `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MemoryType     string             `json:"memory_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Why            string             `json:"why"`
	Tags           []string           `json:"tags"`
	Source         string             `json:"source"`
	AgentActor     string             `json:"agent_actor"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Single memory fetch (UI detail page + audit replay). Filters
// soft-deleted rows.
func (q *Queries) GetMemory(ctx context.Context, id pgtype.UUID) (GetMemoryRow, error) {
	row := q.db.QueryRow(ctx, getMemory, id)
	var i GetMemoryRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.UserID,
		&i.ProjectID,
		&i.MemoryType,
		&i.Title,
		&i.Body,
		&i.Why,
		&i.Tags,
		&i.Source,
		&i.AgentActor,
		&i.ConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMemory = `-- name: InsertMemory :one

insert into memories (
  id, scope, user_id, project_id, memory_type,
  title, body, why, tags,
  source, agent_actor, conversation_id,
  created_at, updated_at
)
values (
  $1::uuid, $2, $3::uuid, $4::uuid, $5,
  $6, $7, $8, $9::text[],
  $10, $11, $12::uuid,
  $13, $13
)
returning
  id::text           as id,
  scope,
  user_id::text      as user_id,
  project_id,
  memory_type,
  title,
  body,
  why,
  tags,
  source,
  agent_actor,
  conversation_id,
  created_at,
  updated_at
`

type InsertMemoryParams struct {
	ID             pgtype.UUID        `json:"id"`
	Scope          string             `json:"scope"`
	UserID         pgtype.UUID        `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MemoryType     string             `json:"memory_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Why            string             `json:"why"`
	Tags           []string           `json:"tags"`
	Source         string             `json:"source"`
	AgentActor     string             `json:"agent_actor"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Now            pgtype.Timestamptz `json:"now"`
}

type InsertMemoryRow struct {
	ID             string             `json:"id"`
	Scope          string             `json:"scope"`
	UserID         string             `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MemoryType     string             `json:"memory_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Why            string             `json:"why"`
	Tags           []string           `json:"tags"`
	Source         string             `json:"source"`
	AgentActor     string             `json:"agent_actor"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// memories.sql — user- and project-scoped memory rows backing the
// spec & memory injection feature (see docs/spec-memory-module.md).
//
// Conventions match spec_fragments.sql in this dir:
//   - application-layer @id::uuid + @now::timestamptz
//   - @param::type casts on every parameter
//   - empty-string / empty-array sentinels skip the corresponding
//     filter so one list query covers unfiltered + filtered views
//   - source / scope / memory_type strings are validated by the Go
//     service layer (specmemory.{Source,Scope,MemoryType} enums);
//     SQL only enforces the scope↔project_id structural CHECK from
//     migration 000004
//
// Two-rail design: user-scope rows live alongside this user only
// (idx_memories_user_scope_active); project-scope rows are shared
// across all users on the project (idx_memories_project_active).
// Per-turn incremental injection therefore uses two separate
// ListXxxSince queries so callers can't accidentally bleed one
// user's user-scope memory into another user's session.
// Single insert path for both UI ("user") and agent ("agent") writes.
// Caller is responsible for:
//   - setting project_id (pgtype.UUID{Valid:false} when scope='user';
//     concrete UUID when scope='project') — the table CHECK enforces
//     the pairing
//   - agent_actor (” for human; 'connector:projectAgentID' for agent)
//   - conversation_id (pgtype.UUID{Valid:false} unless the write
//     originated inside an agent turn)
func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) (InsertMemoryRow, error) {
	row := q.db.QueryRow(ctx, insertMemory,
		arg.ID,
		arg.Scope,
		arg.UserID,
		arg.ProjectID,
		arg.MemoryType,
		arg.Title,
		arg.Body,
		arg.Why,
		arg.Tags,
		arg.Source,
		arg.AgentActor,
		arg.ConversationID,
		arg.Now,
	)
	var i InsertMemoryRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.UserID,
		&i.ProjectID,
		&i.MemoryType,
		&i.Title,
		&i.Body,
		&i.Why,
		&i.Tags,
		&i.Source,
		&i.AgentActor,
		&i.ConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectMemories = `-- name: ListProjectMemories :many
select
  id::text           as id,
  scope,
  user_id::text      as user_id,
  project_id,
  memory_type,
  title,
  body,
  why,
  tags,
  source,
  agent_actor,
  conversation_id,
  created_at,
  updated_at
from memories
where project_id  = $1::uuid
  and scope       = 'project'
  and deleted_at  is null
  and ($2::text = '' or memory_type = $2::text)
  and (cardinality($3::text[]) = 0
       or tags && $3::text[])
order by updated_at desc, id desc
limit $4::int
`

type ListProjectMemoriesParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	MemoryType string      `json:"memory_type"`
	TagFilter  []string    `json:"tag_filter"`
	ItemLimit  int32       `json:"item_limit"`
}

type ListProjectMemoriesRow struct {
	ID             string             `json:"id"`
	Scope          string             `json:"scope"`
	UserID         string             `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MemoryType     string             `json:"memory_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Why            string             `json:"why"`
	Tags           []string           `json:"tags"`
	Source         string             `json:"source"`
	AgentActor     string             `json:"agent_actor"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Per-project listing (shared across all users on the project) for
// the project-scope Memory tab and SessionStart snapshot injection.
// Same filter sentinels as ListUserMemories.
func (q *Queries) ListProjectMemories(ctx context.Context, arg ListProjectMemoriesParams) ([]ListProjectMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listProjectMemories,
		arg.ProjectID,
		arg.MemoryType,
		arg.TagFilter,
		arg.ItemLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMemoriesRow{}
	for rows.Next() {
		var i ListProjectMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.UserID,
			&i.ProjectID,
			&i.MemoryType,
			&i.Title,
			&i.Body,
			&i.Why,
			&i.Tags,
			&i.Source,
			&i.AgentActor,
			&i.ConversationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMemoriesSince = `-- name: ListProjectMemoriesSince :many
select
  id::text           as id,
  scope,
  user_id::text      as user_id,
  project_id,
  memory_type,
  title,
  body,
  why,
  tags,
  source,
  agent_actor,
  conversation_id,
  created_at,
  updated_at
from memories
where project_id  = $1::uuid
  and scope       = 'project'
  and deleted_at  is null
  and updated_at  > $2::timestamptz
order by updated_at asc, id asc
limit $3::int
`

type ListProjectMemoriesSinceParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	Since     pgtype.Timestamptz `json:"since"`
	ItemLimit int32              `json:"item_limit"`
}

type ListProjectMemoriesSinceRow struct {
	ID             string             `json:"id"`
	Scope          string             `json:"scope"`
	UserID         string             `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MemoryType     string             `json:"memory_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Why            string             `json:"why"`
	Tags           []string           `json:"tags"`
	Source         string             `json:"source"`
	AgentActor     string             `json:"agent_actor"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Per-turn incremental cursor for project-scope memories.
// Mirrors ListUserMemoriesSince but scoped by project_id so a
// session bound to project X cannot pick up memories from project Y.
func (q *Queries) ListProjectMemoriesSince(ctx context.Context, arg ListProjectMemoriesSinceParams) ([]ListProjectMemoriesSinceRow, error) {
	rows, err := q.db.Query(ctx, listProjectMemoriesSince, arg.ProjectID, arg.Since, arg.ItemLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMemoriesSinceRow{}
	for rows.Next() {
		var i ListProjectMemoriesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.UserID,
			&i.ProjectID,
			&i.MemoryType,
			&i.Title,
			&i.Body,
			&i.Why,
			&i.Tags,
			&i.Source,
			&i.AgentActor,
			&i.ConversationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemories = `-- name: ListUserMemories :many
select
  id::text           as id,
  scope,
  user_id::text      as user_id,
  project_id,
  memory_type,
  title,
  body,
  why,
  tags,
  source,
  agent_actor,
  conversation_id,
  created_at,
  updated_at
from memories
where user_id     = $1::uuid
  and scope       = 'user'
  and deleted_at  is null
  and ($2::text = '' or memory_type = $2::text)
  and (cardinality($3::text[]) = 0
       or tags && $3::text[])
order by updated_at desc, id desc
limit $4::int
`

type ListUserMemoriesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	MemoryType string      `json:"memory_type"`
	TagFilter  []string    `json:"tag_filter"`
	ItemLimit  int32       `json:"item_limit"`
}

type ListUserMemoriesRow struct {
	ID             string             `json:"id"`
	Scope          string             `json:"scope"`
	UserID         string             `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MemoryType     string             `json:"memory_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Why            string             `json:"why"`
	Tags           []string           `json:"tags"`
	Source         string             `json:"source"`
	AgentActor     string             `json:"agent_actor"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Per-user listing for the user-scope Memory tab in UI and for
// SessionStart snapshot injection. Filters:
//   - @memory_type::text — empty string skips; otherwise exact
//     match (e.g. only 'feedback' rows)
//   - @tag_filter::text[] — empty array skips; otherwise overlap
//
// Order updated_at desc so freshest memories dominate when callers
// cap with @item_limit.
func (q *Queries) ListUserMemories(ctx context.Context, arg ListUserMemoriesParams) ([]ListUserMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listUserMemories,
		arg.UserID,
		arg.MemoryType,
		arg.TagFilter,
		arg.ItemLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMemoriesRow{}
	for rows.Next() {
		var i ListUserMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.UserID,
			&i.ProjectID,
			&i.MemoryType,
			&i.Title,
			&i.Body,
			&i.Why,
			&i.Tags,
			&i.Source,
			&i.AgentActor,
			&i.ConversationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemoriesSince = `-- name: ListUserMemoriesSince :many
select
  id::text           as id,
  scope,
  user_id::text      as user_id,
  project_id,
  memory_type,
  title,
  body,
  why,
  tags,
  source,
  agent_actor,
  conversation_id,
  created_at,
  updated_at
from memories
where user_id     = $1::uuid
  and scope       = 'user'
  and deleted_at  is null
  and updated_at  > $2::timestamptz
order by updated_at asc, id asc
limit $3::int
`

type ListUserMemoriesSinceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Since     pgtype.Timestamptz `json:"since"`
	ItemLimit int32              `json:"item_limit"`
}

type ListUserMemoriesSinceRow struct {
	ID             string             `json:"id"`
	Scope          string             `json:"scope"`
	UserID         string             `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MemoryType     string             `json:"memory_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Why            string             `json:"why"`
	Tags           []string           `json:"tags"`
	Source         string             `json:"source"`
	AgentActor     string             `json:"agent_actor"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Per-turn incremental cursor for user-scope memories. Returns
// rows whose updated_at is strictly greater than the cursor so
// both new inserts and edits surface. Soft-deleted rows are
// excluded; per-turn deletion retraction is a separate query if
// needed later.
func (q *Queries) ListUserMemoriesSince(ctx context.Context, arg ListUserMemoriesSinceParams) ([]ListUserMemoriesSinceRow, error) {
	rows, err := q.db.Query(ctx, listUserMemoriesSince, arg.UserID, arg.Since, arg.ItemLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMemoriesSinceRow{}
	for rows.Next() {
		var i ListUserMemoriesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.UserID,
			&i.ProjectID,
			&i.MemoryType,
			&i.Title,
			&i.Body,
			&i.Why,
			&i.Tags,
			&i.Source,
			&i.AgentActor,
			&i.ConversationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMemory = `-- name: SoftDeleteMemory :exec
update memories
set deleted_at = $1,
    updated_at = $1
where id         = $2::uuid
  and deleted_at is null
`

type SoftDeleteMemoryParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

// Tombstone the memory. Idempotent on already-deleted rows.
// Hard delete is intentionally absent: audit replay needs the body
// to render historical injections.
func (q *Queries) SoftDeleteMemory(ctx context.Context, arg SoftDeleteMemoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteMemory, arg.Now, arg.ID)
	return err
}

const updateMemory = `-- name: UpdateMemory :one
update memories
set title      = $1,
    body       = $2,
    why        = $3,
    tags       = $4::text[],
    updated_at = $5
where id         = $6::uuid
  and deleted_at is null
returning
  id::text           as id,
  scope,
  user_id::text      as user_id,
  project_id,
  memory_type,
  title,
  body,
  why,
  tags,
  source,
  agent_actor,
  conversation_id,
  created_at,
  updated_at
`

type UpdateMemoryParams struct {
	Title string             `json:"title"`
	Body  string             `json:"body"`
	Why   string             `json:"why"`
	Tags  []string           `json:"tags"`
	Now   pgtype.Timestamptz `json:"now"`
	ID    pgtype.UUID        `json:"id"`
}

type UpdateMemoryRow struct {
	ID             string             `json:"id"`
	Scope          string             `json:"scope"`
	UserID         string             `json:"user_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	MemoryType     string             `json:"memory_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Why            string             `json:"why"`
	Tags           []string           `json:"tags"`
	Source         string             `json:"source"`
	AgentActor     string             `json:"agent_actor"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Full-replace update of the editable fields. Provenance fields
// (scope/user_id/project_id/memory_type/source/agent_actor/
// conversation_id) are fixed at insert time and intentionally not
// editable — a "moved" memory should be deleted + re-inserted so
// audit history stays intact. memory_type is excluded because a
// type change usually means the user meant a different memory and
// should re-author it.
func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (UpdateMemoryRow, error) {
	row := q.db.QueryRow(ctx, updateMemory,
		arg.Title,
		arg.Body,
		arg.Why,
		arg.Tags,
		arg.Now,
		arg.ID,
	)
	var i UpdateMemoryRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.UserID,
		&i.ProjectID,
		&i.MemoryType,
		&i.Title,
		&i.Body,
		&i.Why,
		&i.Tags,
		&i.Source,
		&i.AgentActor,
		&i.ConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
