// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: model_catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCatalogModel = `-- name: CreateCatalogModel :one
INSERT INTO models(id, slug, workspace_id, provider_id, name, model_key, context_window, max_output_tokens, provider_type, adapter, credential_mode, created_by, created_at, updated_at)
SELECT $1::uuid, $2, p.workspace_id, p.id, $3, $4, $5, $6, 'agents_api', 'agents_api', 'core', $7::uuid, now(), now()
FROM model_providers p WHERE p.workspace_id = $8::uuid AND p.id = $9::uuid AND p.deleted_at IS NULL
RETURNING id::text, name, model_key, provider_id::text, context_window, max_output_tokens
`

type CreateCatalogModelParams struct {
	ID              pgtype.UUID `json:"id"`
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	ModelKey        string      `json:"model_key"`
	ContextWindow   int32       `json:"context_window"`
	MaxOutputTokens int32       `json:"max_output_tokens"`
	CreatedBy       pgtype.UUID `json:"created_by"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	ProviderID      pgtype.UUID `json:"provider_id"`
}

type CreateCatalogModelRow struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	ModelKey        string `json:"model_key"`
	ProviderID      string `json:"provider_id"`
	ContextWindow   int32  `json:"context_window"`
	MaxOutputTokens int32  `json:"max_output_tokens"`
}

func (q *Queries) CreateCatalogModel(ctx context.Context, arg CreateCatalogModelParams) (CreateCatalogModelRow, error) {
	row := q.db.QueryRow(ctx, createCatalogModel,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.ModelKey,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.CreatedBy,
		arg.WorkspaceID,
		arg.ProviderID,
	)
	var i CreateCatalogModelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ModelKey,
		&i.ProviderID,
		&i.ContextWindow,
		&i.MaxOutputTokens,
	)
	return i, err
}

const createCatalogProvider = `-- name: CreateCatalogProvider :one
INSERT INTO model_providers(id, workspace_id, name, protocol, base_url, encrypted_key)
VALUES ($1::uuid, $2::uuid, $3, $4, $5, $6)
RETURNING id::text, workspace_id::text, name, protocol, base_url, created_at, updated_at
`

type CreateCatalogProviderParams struct {
	ID           pgtype.UUID `json:"id"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	Name         string      `json:"name"`
	Protocol     string      `json:"protocol"`
	BaseUrl      string      `json:"base_url"`
	EncryptedKey []byte      `json:"encrypted_key"`
}

type CreateCatalogProviderRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	Protocol    string             `json:"protocol"`
	BaseUrl     string             `json:"base_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCatalogProvider(ctx context.Context, arg CreateCatalogProviderParams) (CreateCatalogProviderRow, error) {
	row := q.db.QueryRow(ctx, createCatalogProvider,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Protocol,
		arg.BaseUrl,
		arg.EncryptedKey,
	)
	var i CreateCatalogProviderRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCatalogModel = `-- name: DeleteCatalogModel :execrows
UPDATE models SET deleted_at = now(), updated_at = now()
WHERE workspace_id = $1::uuid AND id = $2::uuid AND credential_mode = 'core' AND deleted_at IS NULL
`

type DeleteCatalogModelParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteCatalogModel(ctx context.Context, arg DeleteCatalogModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCatalogModel, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCatalogProvider = `-- name: DeleteCatalogProvider :execrows
UPDATE model_providers SET deleted_at = now(), updated_at = now()
WHERE workspace_id = $1::uuid AND id = $2::uuid AND deleted_at IS NULL
`

type DeleteCatalogProviderParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteCatalogProvider(ctx context.Context, arg DeleteCatalogProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCatalogProvider, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureCatalogCoreSession = `-- name: EnsureCatalogCoreSession :one
INSERT INTO product_core_sessions (id, workspace_id, conversation_id, agent_id, request, provider_snapshot)
SELECT $1::uuid, r.workspace_id, r.conversation_id, r.agent_id, $2::jsonb, $3
FROM agent_runs r WHERE r.id = $4::uuid
ON CONFLICT (conversation_id, agent_id) DO UPDATE SET id = product_core_sessions.id
RETURNING id, workspace_id, conversation_id, agent_id, request, core_session_id, created_at, provider_snapshot
`

type EnsureCatalogCoreSessionParams struct {
	ID               pgtype.UUID `json:"id"`
	Request          []byte      `json:"request"`
	ProviderSnapshot []byte      `json:"provider_snapshot"`
	RunID            pgtype.UUID `json:"run_id"`
}

func (q *Queries) EnsureCatalogCoreSession(ctx context.Context, arg EnsureCatalogCoreSessionParams) (ProductCoreSession, error) {
	row := q.db.QueryRow(ctx, ensureCatalogCoreSession,
		arg.ID,
		arg.Request,
		arg.ProviderSnapshot,
		arg.RunID,
	)
	var i ProductCoreSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.AgentID,
		&i.Request,
		&i.CoreSessionID,
		&i.CreatedAt,
		&i.ProviderSnapshot,
	)
	return i, err
}

const getCatalogCoreSession = `-- name: GetCatalogCoreSession :one
SELECT s.id::text AS id, s.workspace_id::text AS workspace_id, s.core_session_id, s.request, s.provider_snapshot
FROM product_core_sessions s JOIN agent_runs r ON r.conversation_id = s.conversation_id AND r.agent_id = s.agent_id WHERE r.id = $1::uuid
`

type GetCatalogCoreSessionRow struct {
	ID               string `json:"id"`
	WorkspaceID      string `json:"workspace_id"`
	CoreSessionID    string `json:"core_session_id"`
	Request          []byte `json:"request"`
	ProviderSnapshot []byte `json:"provider_snapshot"`
}

func (q *Queries) GetCatalogCoreSession(ctx context.Context, runID pgtype.UUID) (GetCatalogCoreSessionRow, error) {
	row := q.db.QueryRow(ctx, getCatalogCoreSession, runID)
	var i GetCatalogCoreSessionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CoreSessionID,
		&i.Request,
		&i.ProviderSnapshot,
	)
	return i, err
}

const getCatalogModelChoice = `-- name: GetCatalogModelChoice :one
SELECT m.model_key, p.protocol, m.context_window, m.max_output_tokens
FROM models m JOIN model_providers p ON p.id = m.provider_id AND p.workspace_id = m.workspace_id
WHERE m.workspace_id = $1::uuid AND m.id = $2::uuid AND m.credential_mode = 'core'
  AND m.status = 'active' AND m.deleted_at IS NULL AND p.deleted_at IS NULL
`

type GetCatalogModelChoiceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetCatalogModelChoiceRow struct {
	ModelKey        string `json:"model_key"`
	Protocol        string `json:"protocol"`
	ContextWindow   int32  `json:"context_window"`
	MaxOutputTokens int32  `json:"max_output_tokens"`
}

func (q *Queries) GetCatalogModelChoice(ctx context.Context, arg GetCatalogModelChoiceParams) (GetCatalogModelChoiceRow, error) {
	row := q.db.QueryRow(ctx, getCatalogModelChoice, arg.WorkspaceID, arg.ID)
	var i GetCatalogModelChoiceRow
	err := row.Scan(
		&i.ModelKey,
		&i.Protocol,
		&i.ContextWindow,
		&i.MaxOutputTokens,
	)
	return i, err
}

const getCatalogModelExecution = `-- name: GetCatalogModelExecution :one
SELECT m.model_key, p.id::text AS provider_id, p.protocol, p.base_url, p.encrypted_key, m.context_window, m.max_output_tokens
FROM models m JOIN model_providers p ON p.id = m.provider_id AND p.workspace_id = m.workspace_id
WHERE m.workspace_id = $1::uuid AND m.id = $2::uuid AND m.credential_mode = 'core'
  AND m.status = 'active' AND m.deleted_at IS NULL AND p.deleted_at IS NULL
FOR SHARE OF m, p
`

type GetCatalogModelExecutionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetCatalogModelExecutionRow struct {
	ModelKey        string `json:"model_key"`
	ProviderID      string `json:"provider_id"`
	Protocol        string `json:"protocol"`
	BaseUrl         string `json:"base_url"`
	EncryptedKey    []byte `json:"encrypted_key"`
	ContextWindow   int32  `json:"context_window"`
	MaxOutputTokens int32  `json:"max_output_tokens"`
}

func (q *Queries) GetCatalogModelExecution(ctx context.Context, arg GetCatalogModelExecutionParams) (GetCatalogModelExecutionRow, error) {
	row := q.db.QueryRow(ctx, getCatalogModelExecution, arg.WorkspaceID, arg.ID)
	var i GetCatalogModelExecutionRow
	err := row.Scan(
		&i.ModelKey,
		&i.ProviderID,
		&i.Protocol,
		&i.BaseUrl,
		&i.EncryptedKey,
		&i.ContextWindow,
		&i.MaxOutputTokens,
	)
	return i, err
}

const getCatalogRunWorkspace = `-- name: GetCatalogRunWorkspace :one
SELECT workspace_id::text FROM agent_runs WHERE id = $1::uuid
`

func (q *Queries) GetCatalogRunWorkspace(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCatalogRunWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listCatalogModels = `-- name: ListCatalogModels :many
SELECT m.id::text AS id, m.name, m.model_key, m.provider_id::text AS provider_id, p.name AS provider_name, p.protocol, m.context_window, m.max_output_tokens
FROM models m JOIN model_providers p ON p.id = m.provider_id AND p.workspace_id = m.workspace_id
WHERE m.workspace_id = $1::uuid AND m.credential_mode = 'core'
  AND m.deleted_at IS NULL AND m.status = 'active' AND p.deleted_at IS NULL ORDER BY p.name, m.name, m.id
`

type ListCatalogModelsRow struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	ModelKey        string `json:"model_key"`
	ProviderID      string `json:"provider_id"`
	ProviderName    string `json:"provider_name"`
	Protocol        string `json:"protocol"`
	ContextWindow   int32  `json:"context_window"`
	MaxOutputTokens int32  `json:"max_output_tokens"`
}

func (q *Queries) ListCatalogModels(ctx context.Context, workspaceID pgtype.UUID) ([]ListCatalogModelsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogModels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogModelsRow{}
	for rows.Next() {
		var i ListCatalogModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ModelKey,
			&i.ProviderID,
			&i.ProviderName,
			&i.Protocol,
			&i.ContextWindow,
			&i.MaxOutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogProviders = `-- name: ListCatalogProviders :many
SELECT id::text, workspace_id::text, name, protocol, base_url, created_at, updated_at
FROM model_providers WHERE workspace_id = $1::uuid AND deleted_at IS NULL ORDER BY name, id
`

type ListCatalogProvidersRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	Protocol    string             `json:"protocol"`
	BaseUrl     string             `json:"base_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCatalogProviders(ctx context.Context, workspaceID pgtype.UUID) ([]ListCatalogProvidersRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProviders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProvidersRow{}
	for rows.Next() {
		var i ListCatalogProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Protocol,
			&i.BaseUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCatalogModel = `-- name: RenameCatalogModel :one
UPDATE models m SET name = $1, updated_at = now()
FROM model_providers p
WHERE m.workspace_id = $2::uuid AND m.id = $3::uuid
  AND m.credential_mode = 'core' AND m.deleted_at IS NULL AND p.id = m.provider_id AND p.deleted_at IS NULL
RETURNING m.id::text AS id, m.name, m.model_key, m.provider_id::text AS provider_id, m.context_window, m.max_output_tokens
`

type RenameCatalogModelParams struct {
	Name        string      `json:"name"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type RenameCatalogModelRow struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	ModelKey        string `json:"model_key"`
	ProviderID      string `json:"provider_id"`
	ContextWindow   int32  `json:"context_window"`
	MaxOutputTokens int32  `json:"max_output_tokens"`
}

func (q *Queries) RenameCatalogModel(ctx context.Context, arg RenameCatalogModelParams) (RenameCatalogModelRow, error) {
	row := q.db.QueryRow(ctx, renameCatalogModel, arg.Name, arg.WorkspaceID, arg.ID)
	var i RenameCatalogModelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ModelKey,
		&i.ProviderID,
		&i.ContextWindow,
		&i.MaxOutputTokens,
	)
	return i, err
}

const updateCatalogProvider = `-- name: UpdateCatalogProvider :one
UPDATE model_providers SET name = $1, protocol = $2, base_url = $3,
  encrypted_key = coalesce($4::bytea, encrypted_key), updated_at = now()
WHERE workspace_id = $5::uuid AND id = $6::uuid AND deleted_at IS NULL
RETURNING id::text, workspace_id::text, name, protocol, base_url, created_at, updated_at
`

type UpdateCatalogProviderParams struct {
	Name         string      `json:"name"`
	Protocol     string      `json:"protocol"`
	BaseUrl      string      `json:"base_url"`
	EncryptedKey []byte      `json:"encrypted_key"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	ID           pgtype.UUID `json:"id"`
}

type UpdateCatalogProviderRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	Protocol    string             `json:"protocol"`
	BaseUrl     string             `json:"base_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCatalogProvider(ctx context.Context, arg UpdateCatalogProviderParams) (UpdateCatalogProviderRow, error) {
	row := q.db.QueryRow(ctx, updateCatalogProvider,
		arg.Name,
		arg.Protocol,
		arg.BaseUrl,
		arg.EncryptedKey,
		arg.WorkspaceID,
		arg.ID,
	)
	var i UpdateCatalogProviderRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
