// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// workspace 级 Agent 定义表
type Agent struct {
	// Agent ID
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Agent 展示名
	Name string `json:"name"`
	// workspace 内 Agent 标识
	Slug string `json:"slug"`
	// Agent 描述
	Description string `json:"description"`
	// Agent 连接器类型
	ConnectorType string `json:"connector_type"`
	// Agent 可见范围
	Visibility string `json:"visibility"`
	// 启用状态
	Status string `json:"status"`
	// Agent JSON 配置
	Config []byte `json:"config"`
	// 创建人
	CreatedBy pgtype.UUID `json:"created_by"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最近更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=活跃
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Agent capability 绑定表
type AgentCapability struct {
	// 绑定记录 ID
	ID pgtype.UUID `json:"id"`
	// 所属 project_agent
	ProjectAgentID pgtype.UUID `json:"project_agent_id"`
	// 绑定的 capability
	CapabilityID pgtype.UUID `json:"capability_id"`
	// 锁定的版本; RESTRICT 防止误删仍被使用的版本
	CapabilityVersionID pgtype.UUID `json:"capability_version_id"`
	// latest=dispatch 时查 capability 最新版本; pinned=锁 capability_version_id 列
	PinningMode string `json:"pinning_mode"`
	// 绑定启用状态
	Enabled bool `json:"enabled"`
	// 能力实例配置
	Configuration []byte `json:"configuration"`
	// 绑定时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最近修改时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// agent_daemon device_id 到当前 WebSocket owner pod 的租约表
type AgentDaemonDeviceOwner struct {
	// agent_daemon runtime/device id
	DeviceID pgtype.UUID `json:"device_id"`
	// 设备所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 当前持有该 device WebSocket 的 pod id
	OwnerPodID string `json:"owner_pod_id"`
	// 当前 owner pod 的内部可达 URL, 用于跨 pod 转发
	OwnerUrl string `json:"owner_url"`
	// fencing token; 每次 claim 递增, 续租/释放必须匹配
	Generation int64 `json:"generation"`
	// owner 状态: connected / draining / expired
	Status string `json:"status"`
	// 本代 owner 连接建立时间
	ConnectedAt pgtype.Timestamptz `json:"connected_at"`
	// 当前 owner 最近续租/心跳时间
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	// owner 租约过期时间
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Agent 执行记录表
type AgentRun struct {
	// run ID
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属 Project
	ProjectID pgtype.UUID `json:"project_id"`
	// 所属会话
	ConversationID pgtype.UUID `json:"conversation_id"`
	// 触发消息 ID
	TriggerMessageID pgtype.UUID `json:"trigger_message_id"`
	// run 触发来源(WHAT): message=用户消息; agent=另一 agent; scheduled_task=定时任务; webhook=外部事件; issue=工单; manual=管理员手动
	TriggerSource string `json:"trigger_source"`
	// run 触发通道(HOW): web=内置 UI; im=即时通讯; api=外部 API; cron=定时调度; internal=系统内部
	TriggerChannel string `json:"trigger_channel"`
	// 触发源对象类型
	TriggerRefType string `json:"trigger_ref_type"`
	// 触发源对象 ID
	TriggerRefID pgtype.UUID `json:"trigger_ref_id"`
	// 请求方类型
	RequestedByType string `json:"requested_by_type"`
	// 请求方 ID
	RequestedByID pgtype.UUID `json:"requested_by_id"`
	// 本次 run 使用的 project_agent
	ProjectAgentID pgtype.UUID `json:"project_agent_id"`
	// 执行连接器类型快照
	ConnectorType string `json:"connector_type"`
	// 外部运行 ID
	ExternalRunID string `json:"external_run_id"`
	// 承载执行的 runtime
	RuntimeID pgtype.UUID `json:"runtime_id"`
	// 本次 run 工作目录快照
	WorkingDirectory string `json:"working_directory"`
	// run 终态/过渡态: queued=入队; running=执行中; completed/failed=正常终态; cancelled=用户主动取消; interrupted=系统打断(如 runtime crash)
	Status string `json:"status"`
	// run 可见范围
	Visibility string `json:"visibility"`
	// 输出消息 ID
	OutputMessageID pgtype.UUID `json:"output_message_id"`
	// 失败原因
	FailureReason string `json:"failure_reason"`
	// run 元数据
	Metadata []byte `json:"metadata"`
	// 入队时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 开始执行时间
	StartedAt pgtype.Timestamptz `json:"started_at"`
	// 终态时间
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	// 任何字段变更时刷新
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// agent_run 产物表
type AgentRunArtifact struct {
	// 产物 ID
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属 project
	ProjectID pgtype.UUID `json:"project_id"`
	// 所属 run
	AgentRunID pgtype.UUID `json:"agent_run_id"`
	// 产物显示名
	Name string `json:"name"`
	// 产物载体: file=可下载文件; link=外链(URI 为完整 URL); inline=正文随 metadata 内联
	Medium string `json:"medium"`
	// 产物语义分类(free-form,不做 CHECK 约束): report / log / patch / pr_ref / image_thumbnail 等; '=未分类
	Kind string `json:"kind"`
	// 产物 URI
	Uri string `json:"uri"`
	// 产物可见范围
	Visibility string `json:"visibility"`
	// 产物元数据
	Metadata []byte `json:"metadata"`
	// 产物创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// agent_run 流式事件表
type AgentRunEvent struct {
	// 事件行主键
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属 project
	ProjectID pgtype.UUID `json:"project_id"`
	// 所属 run
	AgentRunID pgtype.UUID `json:"agent_run_id"`
	// run 内事件序号
	Sequence int64 `json:"sequence"`
	// 事件类型
	EventKind string `json:"event_kind"`
	// 事件载荷
	Payload []byte `json:"payload"`
	// 事件发生时间
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	// 落库时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 合规审计流水表
type AuditRecord struct {
	// 自增 ID
	ID int64 `json:"id"`
	// 审计来源分类
	Source string `json:"source"`
	// 审计事件类型
	EventType string `json:"event_type"`
	// 触发者类型
	ActorType string `json:"actor_type"`
	// 触发者 ID; system 事件可留空
	ActorID pgtype.UUID `json:"actor_id"`
	// 操作对象类型
	TargetType string `json:"target_type"`
	// 操作对象 ID
	TargetID pgtype.UUID `json:"target_id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属 project
	ProjectID pgtype.UUID `json:"project_id"`
	// 脱敏事件上下文
	Payload []byte `json:"payload"`
	// 事件发生时间
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

// 用户外部身份绑定表
type AuthIdentity struct {
	ID pgtype.UUID `json:"id"`
	// 本地用户
	UserID pgtype.UUID `json:"user_id"`
	// 身份提供方: email=本地邮箱密码 / feishu=飞书登录 / oidc=通用 OIDC
	Provider string `json:"provider"`
	// 外部唯一标识
	Subject string `json:"subject"`
	// 身份附加信息
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Agent capability 目录表
type Capability struct {
	// 能力 ID
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 能力类型: skill=opencode 内置工具脚本; mcp=标准 MCP server
	Type string `json:"type"`
	// 能力名称
	Name string `json:"name"`
	// 能力描述
	Description string `json:"description"`
	// 分类标签(jsonb 字符串数组); 由 capability_tag 表合并而来
	Tags []byte `json:"tags"`
	// workspace=本 workspace 可见 / public=全平台可见。不含 tenant 层级——跨 workspace 共享走 marketplace 流程(000023)而非 visibility 字段
	Visibility string `json:"visibility"`
	// 能力启用状态
	Status string `json:"status"`
	// 发布者
	CreatorID pgtype.UUID `json:"creator_id"`
	// 发布时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最近更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软下线时间戳
	DeprecatedAt pgtype.Timestamptz `json:"deprecated_at"`
	// 软删除时间戳
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// capability 版本表
type CapabilityVersion struct {
	// 版本 ID
	ID pgtype.UUID `json:"id"`
	// 所属 capability
	CapabilityID pgtype.UUID `json:"capability_id"`
	// 版本号
	Version string `json:"version"`
	// 源码仓库 URL
	GitRepoUrl pgtype.Text `json:"git_repo_url"`
	// git tag 或 commit
	GitRef pgtype.Text `json:"git_ref"`
	// 仓库内路径
	Path pgtype.Text `json:"path"`
	// 内联版本内容(per-scaffold rendered); 旧路径回退用
	Content []byte `json:"content"`
	// 导入时的原始粘贴内容快照; 形如 {"format":"json|toml|markdown","body":"…"}
	SourcePayload []byte `json:"source_payload"`
	// canonical_spec 的 schema 版本; v1 起 = 1
	SchemaVersion int16 `json:"schema_version"`
	// 清洗后的规范化结构(canonical.Spec); Renderer 转 per-scaffold rendered;NULL 时 fallback content
	CanonicalSpec []byte `json:"canonical_spec"`
	// Plugin 类型: 对象在 OSS bucket 内的 key;mcp/skill 类型为空字符串
	OssKey string `json:"oss_key"`
	// Plugin 类型: zip 文件 SHA-256 摘要 (64 字符 hex);mcp/skill 类型为空字符串
	Sha256 string `json:"sha256"`
	// 该版本所需凭据清单(数组,快照); 元素形如 {kind, required, description}; kind 对应 user_credentials.kind, 由代码 registry 校验; 与本版本 content 里的 ${PARSAR_CREDENTIAL:<kind>} 占位符对应
	RequiredCredentials []byte `json:"required_credentials"`
	// 版本发布者
	CreatorID pgtype.UUID `json:"creator_id"`
	// 发布时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 会话与上游 connector session 绑定表
type ConnectorSessionBinding struct {
	// 绑定记录 ID
	ID int64 `json:"id"`
	// 会话 ID
	ConversationID string `json:"conversation_id"`
	// connector 类型, 如 opencode/claude_code/codex/http_agent
	ConnectorType string `json:"connector_type"`
	// connector 私有绑定 key, 如 OpenCode pool_key
	BindingKey string `json:"binding_key"`
	// 上游 agent/connector session ID
	UpstreamSessionID string `json:"upstream_session_id"`
	// connector 私有绑定元数据
	Metadata []byte `json:"metadata"`
	// 绑定建立时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最近复用时间
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

// Project 会话表
type Conversation struct {
	// 会话 ID
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属 Project
	ProjectID pgtype.UUID `json:"project_id"`
	// 会话顶层入口: web=内置 UI; im=即时通讯(具体平台见 platform 列); api=外部 API 触发
	Surface string `json:"surface"`
	// 会话形态: thread=单线程对话(web 默认); group=群聊; dm=私聊; oneshot=一次性请求(api 默认)
	Form string `json:"form"`
	// 会话标题
	Title string `json:"title"`
	// 外部平台标识
	Platform string `json:"platform"`
	// 外部会话 ID
	ExternalID string `json:"external_id"`
	// 外部线程 ID
	ExternalThreadID string `json:"external_thread_id"`
	// 来源应用 ID
	SourceAppID string `json:"source_app_id"`
	// 会话状态
	Status string `json:"status"`
	// 会话元数据
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 凭据类型注册表; 管理员可通过 capability 导入 UI 直接新建
type CredentialKind struct {
	// credential kind 主键
	ID pgtype.UUID `json:"id"`
	// 系统内唯一短码; 对应 user_credentials.kind 文本
	Code string `json:"code"`
	// 展示名(中英文同栏); 至少非空
	DisplayName string `json:"display_name"`
	// 类型说明; 展示给最终用户
	Description string `json:"description"`
	// value 校验 schema(预留); v1 不强校验
	ValueSchema []byte `json:"value_schema"`
	// 分类: platform_oauth=平台内置 OAuth provider / platform_model=LLM provider API key / user_defined=管理员临时新增
	Source string `json:"source"`
	// 系统种子标记; built_in=true 不允许删除
	BuiltIn bool `json:"built_in"`
	// 新建管理员; built_in=true 行此列 NULL
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=活跃
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Gateway 外部会话的路由选择状态
type GatewaySession struct {
	ID pgtype.UUID `json:"id"`
	// 外部平台标识，如 feishu/slack/webhook
	Platform string `json:"platform"`
	// 外部会话 ID，如飞书 chat_id
	ExternalID string `json:"external_id"`
	// 外部线程 ID；chat 级选择为空字符串
	ExternalThreadID string `json:"external_thread_id"`
	// 当前选中的 Parsar Agent
	SelectedAgentID pgtype.UUID `json:"selected_agent_id"`
	// Gateway session 元数据
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// user/project 级 memory,agent 自觉写入 + 用户事后审计
type Memory struct {
	// memory 内部 ID
	ID pgtype.UUID `json:"id"`
	// 作用域 (user/project); 取值由 specmemory.Scope 管理
	Scope string `json:"scope"`
	// memory 归属用户; scope=project 时也填,用于排重与审计
	UserID pgtype.UUID `json:"user_id"`
	// 所属 project; scope=user 时为 NULL,scope=project 时必填
	ProjectID pgtype.UUID `json:"project_id"`
	// 类型 (user/feedback/project/reference); 取值由 specmemory.MemoryType 管理
	MemoryType string `json:"memory_type"`
	// 简短标题,可选
	Title string `json:"title"`
	// 主体内容
	Body string `json:"body"`
	// feedback/project 类推荐填写的动因说明
	Why string `json:"why"`
	// 标签数组
	Tags []string `json:"tags"`
	// 来源 (user/agent/auto-review); 取值由 specmemory.Source 管理
	Source string `json:"source"`
	// agent 写入时记录 connector:projectAgentID; 人工写入为空
	AgentActor string `json:"agent_actor"`
	// agent 写入时关联的会话 ID; 会话被删时置 NULL,不连带删 memory
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=未删除
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 会话时间线消息表
type Message struct {
	// 消息 ID
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属 project
	ProjectID pgtype.UUID `json:"project_id"`
	// 所属会话
	ConversationID pgtype.UUID `json:"conversation_id"`
	// 发送方类型: user=真人; agent=Agent 输出; system=Parsar 系统事件; external=外部 IM 用户(未注册)
	SenderType string `json:"sender_type"`
	// 对应 user_id 或 agent_id; system / external 可为空
	SenderID pgtype.UUID `json:"sender_id"`
	// 消息语义类别: message=普通会话消息; artifact=产物消息; system_event=系统事件; error=错误。错误来源(agent/runtime/validation)放 metadata.error.source
	Kind string `json:"kind"`
	// 消息正文渲染格式: text=纯文本; markdown=Markdown; card=结构化卡片(schema 见 metadata.card)
	ContentFormat string `json:"content_format"`
	// 消息可见范围
	Visibility string `json:"visibility"`
	// 消息正文
	Content string `json:"content"`
	// 消息元数据
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 组织级共享 LLM model catalog
type Model struct {
	// 模型主键
	ID pgtype.UUID `json:"id"`
	// 机器可读稳定标识(自动生成, 全局唯一)
	Slug string `json:"slug"`
	// 模型展示名
	Name string `json:"name"`
	// provider 类型: anthropic / openai / ...
	ProviderType string `json:"provider_type"`
	// opencode SDK adapter 包名(@ai-sdk/anthropic 等)
	Adapter string `json:"adapter"`
	// API base URL
	BaseUrl string `json:"base_url"`
	// provider 侧模型 ID
	ModelKey string `json:"model_key"`
	// 凭据模式: inline_secret(共享) / credential_ref(用户私有)
	CredentialMode string `json:"credential_mode"`
	// inline_secret 模式下绑定的共享 secret; NULL=待配置
	SecretID pgtype.UUID `json:"secret_id"`
	// credential_ref 模式下绑定的 credential_kinds.code
	CredentialKindCode pgtype.Text `json:"credential_kind_code"`
	// 模型配置: capabilities/limits/headers/modalities/options 等
	Config []byte `json:"config"`
	// 启用状态: active / disabled
	Status string `json:"status"`
	// 创建人(用于编辑/删除权限校验)
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除标记
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 项目表, 最小业务权限边界
type Project struct {
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 项目展示名
	Name string `json:"name"`
	// workspace 内项目标识
	Slug string `json:"slug"`
	// 项目描述, 展示用
	Description string `json:"description"`
	// 状态: active=活跃 / archived=已归档(只读)
	Status string `json:"status"`
	// 项目级配置
	Config []byte `json:"config"`
	// 创建人
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=未删除
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Agent 与 Project 绑定表
type ProjectAgent struct {
	// 绑定记录 ID
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属 Project; Project 删则级联删绑定
	ProjectID pgtype.UUID `json:"project_id"`
	// 引用的 Agent; Agent 删则级联删绑定
	AgentID pgtype.UUID `json:"agent_id"`
	// 显式绑定的 runtime; NULL=未绑定(dispatch 时报错引导用户去 agent 设置页选择)
	RuntimeID pgtype.UUID `json:"runtime_id"`
	// Project 内 Agent 启用状态
	Status string `json:"status"`
	// Project 级 Agent 覆写配置
	Config []byte `json:"config"`
	// 操作绑定的人
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=有效绑定
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Agent runtime 注册表
type Runtime struct {
	// runtime 主键, 由 server 端生成
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// runtime 类型: local=用户本机 Runner / sandbox=E2B 等远端沙盒 / external=外接 HTTP Agent
	Type string `json:"type"`
	// runtime 名称
	Name string `json:"name"`
	// runtime provider
	Provider string `json:"provider"`
	// 所属用户
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	// runner 版本号
	Version string `json:"version"`
	// runner 主机名
	Hostname string `json:"hostname"`
	// runtime 配置: runner_public_key/runner_credential_hash 等运行态配置(原 metadata 已并入)
	Config []byte `json:"config"`
	// 配对令牌哈希
	PairingTokenHash pgtype.Text `json:"pairing_token_hash"`
	// 配对令牌过期时间
	PairingTokenExpiresAt pgtype.Timestamptz `json:"pairing_token_expires_at"`
	// runtime 连通性: pending_pairing=待配对 / offline=配对后无心跳 / online=心跳正常 / error=runtime 自报故障
	Liveness string `json:"liveness"`
	// 最近心跳时间
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	// 软删除标记; 非空表示已删除
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 统一沙盒实例表。记录 workspace 范围内所有 provider 沙盒(如 E2B): 预热池沙盒(allocation_status=pooled)、已绑定到 project_agent 的持久沙盒(bound)、以及历史终止行(released)。不存 envd_access_token / endpoint URL 等敏感运行态信息; 这些只在进程内存中保存。
type Sandbox struct {
	// 沙盒实例主键
	ID pgtype.UUID `json:"id"`
	// 归属 workspace; 预热池也按 workspace 隔离, 防止 credential / usage / permission 跨租户
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 绑定的 project_agent; pooled 行为空, bound 行必填
	ProjectAgentID pgtype.UUID `json:"project_agent_id"`
	// 沙盒人类可读名(可空), 主要用于 admin UI 展示
	Name pgtype.Text `json:"name"`
	// 与 connector 的 buildPoolKey 输出对齐; pooled 行为空, bound 行必填
	CacheKey pgtype.Text `json:"cache_key"`
	// 后端 provider(E2B 等)的真实沙盒 ID, 全局唯一
	SandboxID string `json:"sandbox_id"`
	// 模板 ID(E2B template_id), 决定沙盒镜像
	TemplateID string `json:"template_id"`
	// 生命周期: spawning=创建中 / running=可用 / renewing=续期中 / killing=终止中 / killed=已正常终止 / killed_orphaned=启动扫描清理 / killed_error=异常终止
	LifecycleStatus string `json:"lifecycle_status"`
	// 归属状态: pooled=workspace 预热池可 claim / bound=已绑定到 project_agent / released=已释放历史行
	AllocationStatus string `json:"allocation_status"`
	// 沙盒续期秒数; Renew 后 provider 生命周期延长到 now + timeout_seconds
	TimeoutSeconds int32 `json:"timeout_seconds"`
	// 自动续期阈值: 0=关闭; >0=剩余生命周期低于该秒数时自动续期
	AutoRenewThresholdSeconds int32 `json:"auto_renew_threshold_seconds"`
	// provider 侧当前生命周期到期时间; 自动续期扫描依赖此字段
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// 最近一次续期成功或 claim handoff 时间
	LastRenewedAt pgtype.Timestamptz `json:"last_renewed_at"`
	// 审计上下文(spawn run_id、E2B 元数据、kill reason、source=pool/fresh 等), 不进入查询
	Metadata []byte `json:"metadata"`
	// 沙盒实例创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最近一次使用/状态更新时间(空闲 TTL 和 admin 列表依赖此字段)
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	// 终止时间; 非空表示沙盒已不可用, 仅作历史记录
	KilledAt pgtype.Timestamptz `json:"killed_at"`
}

// 定时任务: 锚定 project_agent, 到点用独立 session 触发一次 agent run
type ScheduledTask struct {
	ID pgtype.UUID `json:"id"`
	// 触发的 project_agent (runnable 单元)
	ProjectAgentID pgtype.UUID `json:"project_agent_id"`
	// 最近一次 run 的对话 (创建后为 NULL, 每次派发回填)
	ConversationID pgtype.UUID `json:"conversation_id"`
	Name           string      `json:"name"`
	Prompt         string      `json:"prompt"`
	// 标准 5 段 cron 表达式
	CronExpr string `json:"cron_expr"`
	// IANA 时区, 解释 cron_expr
	Timezone string `json:"timezone"`
	Enabled  bool   `json:"enabled"`
	// phase 2 投递目标群; null = web only
	FeishuChatID   pgtype.Text `json:"feishu_chat_id"`
	FeishuChatName pgtype.Text `json:"feishu_chat_name"`
	// 调度器算出的下次触发 (UTC)
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	LastRunAt pgtype.Timestamptz `json:"last_run_at"`
	// 最近一次派发的 agent_run
	LastRunID  pgtype.UUID `json:"last_run_id"`
	LastStatus string      `json:"last_status"`
	// 连续失败计数, 到阈值自动停用
	ConsecutiveFailures int32 `json:"consecutive_failures"`
	// 多 pod claim 租约时间
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
	// 多 pod claim 持有者
	ClaimedBy string `json:"claimed_by"`
	// 执行身份 = 创建者
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 组织级加密凭据表(共享 catalog)
type Secret struct {
	// secret 主键
	ID pgtype.UUID `json:"id"`
	// 机器可读的稳定标识(自动生成, 全局唯一)
	Slug string `json:"slug"`
	// secret 展示名(可重复, 可修改)
	Name string `json:"name"`
	// secret 用途分类: model_provider/runtime/capability_inline/feishu_bot
	Kind string `json:"kind"`
	// 提供方标识
	Provider string `json:"provider"`
	// 认证类型
	AuthType string `json:"auth_type"`
	// 加密后的凭证 payload
	EncryptedPayload []byte `json:"encrypted_payload"`
	// 包封密钥版本
	KeyVersion string `json:"key_version"`
	// 非敏感元数据
	Metadata []byte `json:"metadata"`
	// 启用状态: active=可用 / disabled=管理员禁用
	Status string `json:"status"`
	// 创建人
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除标记; 非空表示已删除
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// workspace 级 spec 片段,每条独立可注入可编辑
type SpecFragment struct {
	// fragment 内部 ID
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 片段标题
	Title string `json:"title"`
	// 片段 markdown 正文
	Body string `json:"body"`
	// 标签数组,未来用于按 tag 智能注入
	Tags []string `json:"tags"`
	// 来源类别 (manual/agent/import); 取值由 specmemory.Source 管理
	Source string `json:"source"`
	// 人工创建者 user_id; agent 写入时为 NULL
	CreatedBy pgtype.UUID `json:"created_by"`
	// agent 写入时记录 connector:projectAgentID; 人工创建时为空字符串
	AgentActor string             `json:"agent_actor"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=未删除
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// LLM 调用用量记录表
type UsageLog struct {
	// 计费记录主键
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属 project
	ProjectID pgtype.UUID `json:"project_id"`
	// 关联 run
	AgentRunID pgtype.UUID `json:"agent_run_id"`
	// provider 标识
	Provider string `json:"provider"`
	// 模型 key
	Model string `json:"model"`
	// 输入 token 数, 非负
	InputTokens int32 `json:"input_tokens"`
	// 输出 token 数, 非负
	OutputTokens int32 `json:"output_tokens"`
	// 折算成本(USD)
	CostUsd pgtype.Numeric `json:"cost_usd"`
	// 原始调用元数据
	Raw []byte `json:"raw"`
	// 记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 平台核心人员表
type User struct {
	// 内部用户 ID
	ID pgtype.UUID `json:"id"`
	// 业务唯一标识
	Email string `json:"email"`
	// 用户显示名
	Name string `json:"name"`
	// 账号状态: active=正常 / disabled=被禁用
	Status string `json:"status"`
	// 注册时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最近修改时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=未删除
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 用户外部能力凭据表
type UserCredential struct {
	// 凭据 ID
	ID pgtype.UUID `json:"id"`
	// 所属用户
	UserID pgtype.UUID `json:"user_id"`
	// 凭据类型; 由代码 registry 校验
	Kind string `json:"kind"`
	// 凭据展示名
	DisplayName string `json:"display_name"`
	// 加密后的凭据密文
	Ciphertext []byte `json:"ciphertext"`
	// 加密密钥版本
	KeyVersion string `json:"key_version"`
	// 最近使用时间
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	// 最近修改时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 用户登录会话表
type UserSession struct {
	// 会话 token
	ID string `json:"id"`
	// 会话所属用户
	UserID pgtype.UUID `json:"user_id"`
	// 登录设备 UA
	UserAgent string `json:"user_agent"`
	// 登录来源 IP
	Ip string `json:"ip"`
	// 会话创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最近请求时间
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	// 过期时间
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// 主动注销时间; NULL=未撤销
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// 团队级租户容器
type Workspace struct {
	// workspace 内部 ID
	ID pgtype.UUID `json:"id"`
	// 展示名
	Name string `json:"name"`
	// URL/CLI 标识
	Slug string `json:"slug"`
	// 可见性: public=可被其他用户发现并申请加入 / private=仅邀请
	Visibility string `json:"visibility"`
	// workspace JSON 配置
	Config []byte `json:"config"`
	// 创建人
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=未删除
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// workspace 成员与角色表(含申请状态机)
type WorkspaceMember struct {
	ID pgtype.UUID `json:"id"`
	// 所属 workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// 所属用户
	UserID pgtype.UUID `json:"user_id"`
	// 工作区角色: owner=拥有者 / admin=管理员 / member=普通成员 / viewer=只读
	Role string `json:"role"`
	// 成员状态: pending=待审批 / active=正式成员 / rejected=申请被拒(保留行做审计)
	Status string `json:"status"`
	// 用户提交申请时的理由(可空); active 行无意义
	RequestReason pgtype.Text `json:"request_reason"`
	// 审批人 user_id(同意或拒绝时填入)
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
	// 审批时间(同意或拒绝时填入)
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// 软删除时间戳; NULL=当前有效成员
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
