// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Workspace-level Agent definition table
type Agent struct {
	// Agent ID
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Agent display name
	Name string `json:"name"`
	// Agent identifier within the workspace
	Slug string `json:"slug"`
	// Agent description
	Description string `json:"description"`
	// Agent connector type
	ConnectorType string `json:"connector_type"`
	// Agent visibility scope
	Visibility string `json:"visibility"`
	// Enabled state
	Status string `json:"status"`
	// Agent JSON config
	Config []byte `json:"config"`
	// Explicitly bound runtime; NULL = unbound (dispatch errors out and points the user to the agent settings page)
	RuntimeID pgtype.UUID `json:"runtime_id"`
	// Created by
	CreatedBy pgtype.UUID `json:"created_by"`
	// Created at
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last updated at
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp; NULL = active
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Per-agent switch for built-in capabilities; no row = default enabled, enabled=false = this Agent turned it off
type AgentBuiltinCapability struct {
	AgentID pgtype.UUID `json:"agent_id"`
	// Stable identifier for the built-in capability (e.g. parsar_chat_history)
	CapabilityKey string `json:"capability_key"`
	// Whether this built-in capability is enabled for this agent
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Agent capability binding table
type AgentCapability struct {
	// Binding record ID
	ID pgtype.UUID `json:"id"`
	// Owning agent
	AgentID pgtype.UUID `json:"agent_id"`
	// Bound capability
	CapabilityID pgtype.UUID `json:"capability_id"`
	// Pinned version; RESTRICT prevents deletion of a version still in use
	CapabilityVersionID pgtype.UUID `json:"capability_version_id"`
	// latest = look up the capability's latest version at dispatch; pinned = lock the capability_version_id column
	PinningMode string `json:"pinning_mode"`
	// Binding enabled state
	Enabled bool `json:"enabled"`
	// Capability instance configuration
	Configuration []byte `json:"configuration"`
	// Binding time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last updated at
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Lease from agent_daemon device_id to its current WebSocket owner pod
type AgentDaemonDeviceOwner struct {
	// agent_daemon runtime/device id
	DeviceID pgtype.UUID `json:"device_id"`
	// Owning workspace of the device
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Pod id currently holding this device's WebSocket
	OwnerPodID string `json:"owner_pod_id"`
	// Internally reachable URL of the current owner pod, used for cross-pod forwarding
	OwnerUrl string `json:"owner_url"`
	// Fencing token; incremented on every claim, renew/release must match
	Generation int64 `json:"generation"`
	// Owner status: connected / draining / expired
	Status string `json:"status"`
	// Connection time of the current generation
	ConnectedAt pgtype.Timestamptz `json:"connected_at"`
	// Most recent renew/heartbeat time from the current owner
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	// Owner lease expiration time
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Agent execution records
type AgentRun struct {
	// Run ID
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Owning conversation
	ConversationID pgtype.UUID `json:"conversation_id"`
	// Triggering message ID
	TriggerMessageID pgtype.UUID `json:"trigger_message_id"`
	// Run trigger source (WHAT): message = user message; agent = another agent; scheduled_task; webhook = external event; issue = ticket; manual = admin manual
	TriggerSource string `json:"trigger_source"`
	// Run trigger channel (HOW): web = built-in UI; im = instant messaging; api = external API; cron = scheduled; internal = system internal
	TriggerChannel string `json:"trigger_channel"`
	// Trigger source object type
	TriggerRefType string `json:"trigger_ref_type"`
	// Trigger source object ID
	TriggerRefID pgtype.UUID `json:"trigger_ref_id"`
	// Requester type
	RequestedByType string `json:"requested_by_type"`
	// Requester ID
	RequestedByID pgtype.UUID `json:"requested_by_id"`
	// Agent used for this run
	AgentID pgtype.UUID `json:"agent_id"`
	// Connector type snapshot
	ConnectorType string `json:"connector_type"`
	// External run ID
	ExternalRunID string `json:"external_run_id"`
	// Runtime carrying execution
	RuntimeID pgtype.UUID `json:"runtime_id"`
	// Working-directory snapshot for this run
	WorkingDirectory string `json:"working_directory"`
	// Run terminal/transitional state: queued; running; completed/failed (normal terminal); cancelled (user-initiated); interrupted (system interrupt, e.g. runtime crash)
	Status string `json:"status"`
	// Run visibility scope
	Visibility string `json:"visibility"`
	// Output message ID
	OutputMessageID pgtype.UUID `json:"output_message_id"`
	// Failure reason
	FailureReason string `json:"failure_reason"`
	// Run metadata
	Metadata []byte `json:"metadata"`
	// Enqueue time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Execution start time
	StartedAt pgtype.Timestamptz `json:"started_at"`
	// Terminal state time
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	// Refreshed on any field change
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Artifacts produced by an agent_run
type AgentRunArtifact struct {
	// Artifact ID
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Owning run
	AgentRunID pgtype.UUID `json:"agent_run_id"`
	// Artifact display name
	Name string `json:"name"`
	// Artifact medium: file = downloadable file; link = external link (URI is a full URL); inline = body inlined via metadata
	Medium string `json:"medium"`
	// Artifact semantic classification (free-form, no CHECK constraint): report / log / patch / pr_ref / image_thumbnail / ...; '' = uncategorized
	Kind string `json:"kind"`
	// Artifact URI
	Uri string `json:"uri"`
	// Artifact visibility scope
	Visibility string `json:"visibility"`
	// Artifact metadata
	Metadata []byte `json:"metadata"`
	// Artifact creation time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Streaming events for an agent_run
type AgentRunEvent struct {
	// Event row primary key
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Owning run
	AgentRunID pgtype.UUID `json:"agent_run_id"`
	// Sequence number within the run
	Sequence int64 `json:"sequence"`
	// Event type
	EventKind string `json:"event_kind"`
	// Event payload
	Payload []byte `json:"payload"`
	// Event occurrence time
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	// Persistence time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Compliance audit stream
type AuditRecord struct {
	// Auto-increment ID
	ID int64 `json:"id"`
	// Audit source classification
	Source string `json:"source"`
	// Audit event type
	EventType string `json:"event_type"`
	// Actor type
	ActorType string `json:"actor_type"`
	// Actor ID; may be null for system events
	ActorID pgtype.UUID `json:"actor_id"`
	// Target object type
	TargetType string `json:"target_type"`
	// Target object ID
	TargetID pgtype.UUID `json:"target_id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Redacted event context
	Payload []byte `json:"payload"`
	// Event occurrence time
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

// External identity bindings for a user
type AuthIdentity struct {
	ID pgtype.UUID `json:"id"`
	// Local user
	UserID pgtype.UUID `json:"user_id"`
	// Identity provider: email = local email/password / feishu = Feishu login / oidc = generic OIDC
	Provider string `json:"provider"`
	// External unique identifier
	Subject string `json:"subject"`
	// Identity-provider profile. provider=email uses {"password_hash":"<bcrypt>","hashed_at":"<RFC3339>","last_used_at":"<RFC3339>"}; OIDC providers stash the userinfo response.
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Agent capability catalog
type Capability struct {
	// Capability ID
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Capability type: skill = opencode built-in tool script; mcp = standard MCP server
	Type string `json:"type"`
	// Capability name
	Name string `json:"name"`
	// Capability description
	Description string `json:"description"`
	// Categorization tags (jsonb string array); merged in from the capability_tag table
	Tags []byte `json:"tags"`
	// workspace = visible to this workspace / public = visible platform-wide. No tenant tier -- cross-workspace sharing goes through the marketplace flow (000023) rather than the visibility field
	Visibility string `json:"visibility"`
	// Capability enabled state
	Status string `json:"status"`
	// Publisher
	CreatorID pgtype.UUID `json:"creator_id"`
	// Publish time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last updated at
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-deprecation timestamp
	DeprecatedAt pgtype.Timestamptz `json:"deprecated_at"`
	// Soft-delete timestamp
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// PG storage backend for capability plugin/skill zips (enabled when PARSAR_BLOB_BACKEND=pg)
type CapabilityBlob struct {
	// Opaque storage reference = value of capability_version.oss_key (PG backend shape: pg:<uuid>)
	StorageRef string `json:"storage_ref"`
	// Owning workspace; PG backend uses this for cross-tenant ownership checks
	WorkspaceID string `json:"workspace_id"`
	// Raw zip bytes (<= 64 MiB, upper bound enforced in the application layer)
	Bytes []byte `json:"bytes"`
	// SHA-256 digest of the zip (64-char hex), computed on write
	Sha256 string `json:"sha256"`
	// Zip byte count; used by Stat
	SizeBytes int64 `json:"size_bytes"`
	// Write time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Capability versions
type CapabilityVersion struct {
	// Version ID
	ID pgtype.UUID `json:"id"`
	// Owning capability
	CapabilityID pgtype.UUID `json:"capability_id"`
	// Version string
	Version string `json:"version"`
	// Source repo URL
	GitRepoUrl pgtype.Text `json:"git_repo_url"`
	// git tag or commit
	GitRef pgtype.Text `json:"git_ref"`
	// Path within the repo
	Path pgtype.Text `json:"path"`
	// Inline version content (per-scaffold rendered); legacy fallback path
	Content []byte `json:"content"`
	// Snapshot of the raw pasted content at import time; shape {"format":"json|toml|markdown","body":"…"}
	SourcePayload []byte `json:"source_payload"`
	// canonical_spec schema version; = 1 starting from v1
	SchemaVersion int16 `json:"schema_version"`
	// Normalized structure after cleaning (canonical.Spec); Renderer turns it into per-scaffold rendered; falls back to content when NULL
	CanonicalSpec []byte `json:"canonical_spec"`
	// Plugin type: object key within the OSS bucket; empty string for mcp/skill types
	OssKey string `json:"oss_key"`
	// Plugin type: SHA-256 digest of the zip file (64-char hex); empty string for mcp/skill types
	Sha256 string `json:"sha256"`
	// Credential requirements for this version (array snapshot); each element shaped {kind, required, description}; kind matches user_credentials.kind and is validated against the code registry; corresponds to ${PARSAR_CREDENTIAL:<kind>} placeholders in this version's content
	RequiredCredentials []byte `json:"required_credentials"`
	// Version publisher
	CreatorID pgtype.UUID `json:"creator_id"`
	// Publish time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Conversation to upstream connector session bindings
type ConnectorSessionBinding struct {
	// Binding record ID
	ID int64 `json:"id"`
	// Conversation ID
	ConversationID string `json:"conversation_id"`
	// Connector type, e.g. opencode/claude_code/codex/http_agent
	ConnectorType string `json:"connector_type"`
	// Connector-private binding key, e.g. OpenCode pool_key
	BindingKey string `json:"binding_key"`
	// Upstream agent/connector session ID
	UpstreamSessionID string `json:"upstream_session_id"`
	// Connector-private binding metadata
	Metadata []byte `json:"metadata"`
	// Binding creation time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Most recent reuse time
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

// Conversation table
type Conversation struct {
	// Conversation ID
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Top-level entry point: web = built-in UI; im = instant messaging (see platform column for details); api = external API trigger
	Surface string `json:"surface"`
	// Conversation form: thread = single-threaded (web default); group = group chat; dm = direct message; oneshot = one-shot request (api default)
	Form string `json:"form"`
	// Conversation title
	Title string `json:"title"`
	// External platform identifier
	Platform string `json:"platform"`
	// External conversation ID
	ExternalID string `json:"external_id"`
	// External thread ID
	ExternalThreadID string `json:"external_thread_id"`
	// Source app ID
	SourceAppID string `json:"source_app_id"`
	// Conversation status
	Status string `json:"status"`
	// Conversation metadata
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Credential-type registry; admins can add new kinds directly via the capability import UI
type CredentialKind struct {
	// Credential kind primary key
	ID pgtype.UUID `json:"id"`
	// Globally unique short code; matches user_credentials.kind text
	Code string `json:"code"`
	// Display name (single column for CN/EN); required non-empty
	DisplayName string `json:"display_name"`
	// Type description; shown to end users
	Description string `json:"description"`
	// Value validation schema (reserved); v1 does not enforce it
	ValueSchema []byte `json:"value_schema"`
	// Classification: platform_oauth = built-in OAuth provider / platform_model = LLM provider API key / user_defined = ad-hoc admin addition
	Source string `json:"source"`
	// System-seed flag; built_in=true rows cannot be deleted
	BuiltIn bool `json:"built_in"`
	// Admin who added the row; NULL on built_in=true rows
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp; NULL = active
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Route-selection state for external Gateway conversations
type GatewaySession struct {
	ID pgtype.UUID `json:"id"`
	// External platform identifier, e.g. feishu/slack/webhook
	Platform string `json:"platform"`
	// External conversation ID, e.g. Feishu chat_id
	ExternalID string `json:"external_id"`
	// External thread ID; empty string for chat-level selection
	ExternalThreadID string `json:"external_thread_id"`
	// Currently selected Parsar Agent
	SelectedAgentID pgtype.UUID `json:"selected_agent_id"`
	// Gateway session metadata
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// user/workspace-level memory, self-written by agents + audited by users afterwards
type Memory struct {
	// Internal memory ID
	ID pgtype.UUID `json:"id"`
	// Scope (user/workspace); values managed by specmemory.Scope
	Scope string `json:"scope"`
	// Owning user; also set when scope=workspace, for dedup and audit
	UserID pgtype.UUID `json:"user_id"`
	// Owning workspace; NULL when scope=user, required when scope=workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Type (user/feedback/workspace/reference); values managed by specmemory.MemoryType
	MemoryType string `json:"memory_type"`
	// Short title, optional
	Title string `json:"title"`
	// Main body
	Body string `json:"body"`
	// Recommended rationale for feedback/workspace types
	Why string `json:"why"`
	// Tag array
	Tags []string `json:"tags"`
	// Source (user/agent/auto-review); values managed by specmemory.Source
	Source string `json:"source"`
	// On agent writes, records connector:agentID; empty on human writes
	AgentActor string `json:"agent_actor"`
	// Associated conversation ID on agent writes; set to NULL when the conversation is deleted, memory is not cascade-deleted
	ConversationID pgtype.UUID        `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp; NULL = not deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Conversation timeline messages
type Message struct {
	// Message ID
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Owning conversation
	ConversationID pgtype.UUID `json:"conversation_id"`
	// Sender type: user = human; agent = Agent output; system = Parsar system event; external = external IM user (unregistered)
	SenderType string `json:"sender_type"`
	// Corresponding user_id or agent_id; system / external may be null
	SenderID pgtype.UUID `json:"sender_id"`
	// Message semantic kind: message = normal conversation message; artifact = artifact message; system_event = system event; error. Error source (agent/runtime/validation) lives in metadata.error.source
	Kind string `json:"kind"`
	// Message body rendering format: text = plain text; markdown; card = structured card (schema under metadata.card)
	ContentFormat string `json:"content_format"`
	// Message visibility scope
	Visibility string `json:"visibility"`
	// Message body
	Content string `json:"content"`
	// Message metadata
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Organization-level shared LLM model catalog
type Model struct {
	// Model primary key
	ID pgtype.UUID `json:"id"`
	// Machine-readable stable identifier (auto-generated, globally unique)
	Slug string `json:"slug"`
	// Model display name
	Name string `json:"name"`
	// Provider type: anthropic / openai / ...
	ProviderType string `json:"provider_type"`
	// opencode SDK adapter package name (@ai-sdk/anthropic, ...)
	Adapter string `json:"adapter"`
	// API base URL
	BaseUrl string `json:"base_url"`
	// Provider-side model ID
	ModelKey string `json:"model_key"`
	// Credential mode: inline_secret (shared) / credential_ref (user-private)
	CredentialMode string `json:"credential_mode"`
	// Shared secret bound under inline_secret mode; NULL = not yet configured
	SecretID pgtype.UUID `json:"secret_id"`
	// credential_kinds.code bound under credential_ref mode
	CredentialKindCode pgtype.Text `json:"credential_kind_code"`
	// Model config: capabilities/limits/headers/modalities/options/etc.
	Config []byte `json:"config"`
	// Enabled state: active / disabled
	Status string `json:"status"`
	// Created by (used for edit/delete permission checks)
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete marker
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Agent runtime registry
type Runtime struct {
	// Runtime primary key, generated on the server side
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Runtime type: local = user local Runner / sandbox = E2B or other remote sandbox / external = external HTTP Agent
	Type string `json:"type"`
	// Runtime name
	Name string `json:"name"`
	// Runtime provider
	Provider string `json:"provider"`
	// Owning user
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	// Runner version
	Version string `json:"version"`
	// Runner hostname
	Hostname string `json:"hostname"`
	// Runtime config: runner_public_key/runner_credential_hash and other runtime-state fields (formerly metadata, now merged in)
	Config []byte `json:"config"`
	// Pairing token hash
	PairingTokenHash pgtype.Text `json:"pairing_token_hash"`
	// Pairing token expiration time
	PairingTokenExpiresAt pgtype.Timestamptz `json:"pairing_token_expires_at"`
	// Runtime connectivity: pending_pairing / offline = no heartbeat after pairing / online = heartbeat healthy / error = runtime reported failure
	Liveness string `json:"liveness"`
	// Most recent heartbeat time
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete marker; non-null means deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Unified sandbox instance table. Records every provider sandbox (e.g. E2B) inside a workspace: pre-warmed pool sandboxes (allocation_status=pooled), sandboxes already bound to an agent (bound), and historically terminated rows (released). Does not store sensitive runtime info such as envd_access_token / endpoint URL; those live only in process memory.
type Sandbox struct {
	// Sandbox instance primary key
	ID pgtype.UUID `json:"id"`
	// Owning workspace; the pre-warm pool is also isolated per workspace to prevent credential / usage / permission bleed across tenants
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Bound agent; empty on pooled rows, required on bound rows
	AgentID pgtype.UUID `json:"agent_id"`
	// Human-readable sandbox name (nullable), mainly for admin UI display
	Name pgtype.Text `json:"name"`
	// Aligned with the connector's buildPoolKey output; empty on pooled rows, required on bound rows
	CacheKey pgtype.Text `json:"cache_key"`
	// True sandbox ID from the backend provider (E2B etc.), globally unique
	SandboxID string `json:"sandbox_id"`
	// Template ID (E2B template_id) determining the sandbox image
	TemplateID string `json:"template_id"`
	// Lifecycle: spawning = creating / running = usable / renewing = renewing / killing = terminating / killed = terminated normally / killed_orphaned = cleaned up by startup scan / killed_error = terminated abnormally
	LifecycleStatus string `json:"lifecycle_status"`
	// Allocation state: pooled = pre-warmed for workspace, claimable / bound = bound to an agent / released = historically released row
	AllocationStatus string `json:"allocation_status"`
	// Sandbox renewal seconds; after Renew the provider lifecycle extends to now + timeout_seconds
	TimeoutSeconds int32 `json:"timeout_seconds"`
	// Auto-renew threshold: 0 = disabled; >0 = auto-renew when the remaining lifetime drops below this many seconds
	AutoRenewThresholdSeconds int32 `json:"auto_renew_threshold_seconds"`
	// Current provider-side lifecycle expiration; auto-renew scan depends on this column
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Most recent successful renew or claim handoff time
	LastRenewedAt pgtype.Timestamptz `json:"last_renewed_at"`
	// Audit context (spawn run_id, E2B metadata, kill reason, source=pool/fresh, etc.); not part of queries
	Metadata []byte `json:"metadata"`
	// Sandbox instance creation time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Most recent use / state-update time (idle TTL and admin list depend on this column)
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	// Termination time; non-null means the sandbox is unusable and kept only for history
	KilledAt pgtype.Timestamptz `json:"killed_at"`
}

// Scheduled tasks: anchored on an agent, fires one agent run in its own session when due
type ScheduledTask struct {
	ID pgtype.UUID `json:"id"`
	// Agent to trigger (runnable unit)
	AgentID pgtype.UUID `json:"agent_id"`
	// Conversation of the most recent run (NULL when created, backfilled on each dispatch)
	ConversationID pgtype.UUID `json:"conversation_id"`
	Name           string      `json:"name"`
	Prompt         string      `json:"prompt"`
	// Standard 5-field cron expression
	CronExpr string `json:"cron_expr"`
	// IANA timezone used to interpret cron_expr
	Timezone string `json:"timezone"`
	Enabled  bool   `json:"enabled"`
	// Phase 2 delivery target chat; null = web only
	FeishuChatID   pgtype.Text `json:"feishu_chat_id"`
	FeishuChatName pgtype.Text `json:"feishu_chat_name"`
	// Next-fire time computed by the scheduler (UTC)
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	LastRunAt pgtype.Timestamptz `json:"last_run_at"`
	// Most recently dispatched agent_run
	LastRunID  pgtype.UUID `json:"last_run_id"`
	LastStatus string      `json:"last_status"`
	// Consecutive failure count; auto-disables at threshold
	ConsecutiveFailures int32 `json:"consecutive_failures"`
	// Multi-pod claim lease time
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
	// Multi-pod claim holder
	ClaimedBy string `json:"claimed_by"`
	// Execution identity = creator
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Organization-level encrypted credential table (shared catalog)
type Secret struct {
	// Secret primary key
	ID pgtype.UUID `json:"id"`
	// Machine-readable stable identifier (auto-generated, globally unique)
	Slug string `json:"slug"`
	// Secret display name (may repeat, may be edited)
	Name string `json:"name"`
	// Secret usage classification: model_provider/runtime/capability_inline/feishu_bot
	Kind string `json:"kind"`
	// Provider identifier
	Provider string `json:"provider"`
	// Auth type
	AuthType string `json:"auth_type"`
	// Encrypted credential payload
	EncryptedPayload []byte `json:"encrypted_payload"`
	// Wrapping key version
	KeyVersion string `json:"key_version"`
	// Non-sensitive metadata
	Metadata []byte `json:"metadata"`
	// Enabled state: active = usable / disabled = admin-disabled
	Status string `json:"status"`
	// Created by
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete marker; non-null means deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Workspace-level spec fragments, each independently injectable and editable
type SpecFragment struct {
	// Internal fragment ID
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Fragment title
	Title string `json:"title"`
	// Fragment markdown body
	Body string `json:"body"`
	// Tag array, future use for smart injection by tag
	Tags []string `json:"tags"`
	// Source category (manual/agent/import); values managed by specmemory.Source
	Source string `json:"source"`
	// Human creator user_id; NULL on agent writes
	CreatedBy pgtype.UUID `json:"created_by"`
	// On agent writes, records connector:agentID; empty string on human creation
	AgentActor string             `json:"agent_actor"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp; NULL = not deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// LLM call usage records
type UsageLog struct {
	// Billing record primary key
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Associated run
	AgentRunID pgtype.UUID `json:"agent_run_id"`
	// Provider identifier
	Provider string `json:"provider"`
	// Model key
	Model string `json:"model"`
	// Input token count, non-negative
	InputTokens int32 `json:"input_tokens"`
	// Output token count, non-negative
	OutputTokens int32 `json:"output_tokens"`
	// Converted cost (USD)
	CostUsd pgtype.Numeric `json:"cost_usd"`
	// Raw call metadata
	Raw []byte `json:"raw"`
	// Record creation time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Platform-wide user table
type User struct {
	// Internal user ID
	ID pgtype.UUID `json:"id"`
	// Business-unique identifier
	Email string `json:"email"`
	// User display name
	Name string `json:"name"`
	// Account status: active = normal / disabled = banned
	Status string `json:"status"`
	// Registration time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last updated at
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp; NULL = not deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// User-owned external capability credentials
type UserCredential struct {
	// Credential ID
	ID pgtype.UUID `json:"id"`
	// Owning user
	UserID pgtype.UUID `json:"user_id"`
	// Credential type; validated against the code-side registry
	Kind string `json:"kind"`
	// Credential display name
	DisplayName string `json:"display_name"`
	// Encrypted credential ciphertext
	Ciphertext []byte `json:"ciphertext"`
	// Encryption key version
	KeyVersion string `json:"key_version"`
	// Most recent use time
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	// Last updated at
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// User login sessions
type UserSession struct {
	// Session token
	ID string `json:"id"`
	// Owning user
	UserID pgtype.UUID `json:"user_id"`
	// Login device UA
	UserAgent string `json:"user_agent"`
	// Login source IP
	Ip string `json:"ip"`
	// Session creation time
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Most recent request time
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	// Expiration time
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Explicit logout time; NULL = not revoked
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Team-level tenant container
type Workspace struct {
	// Internal workspace ID
	ID pgtype.UUID `json:"id"`
	// Display name
	Name string `json:"name"`
	// URL/CLI identifier
	Slug string `json:"slug"`
	// Visibility: public = discoverable and joinable by request / private = invite-only
	Visibility string `json:"visibility"`
	// Workspace JSON config
	Config []byte `json:"config"`
	// Created by
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp; NULL = not deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Workspace-level IM connector bindings (feishu/slack/discord stored together)
type WorkspaceImConnector struct {
	// Connector primary key
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// IM platform: feishu / slack / discord / teams
	Platform string `json:"platform"`
	// Platform app ID (known at config time; universal join key for workspace-bot)
	AppID string `json:"app_id"`
	// Whether enabled (only then does the reconciler establish an inbound connection)
	Enabled bool `json:"enabled"`
	// Non-sensitive config + secret references (*_ref points to secrets.id; includes event_mode/intents/etc.)
	Config []byte `json:"config"`
	// Created by
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp; NULL = active
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Workspace members and roles (with join-request state machine)
type WorkspaceMember struct {
	ID pgtype.UUID `json:"id"`
	// Owning workspace
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	// Owning user
	UserID pgtype.UUID `json:"user_id"`
	// Workspace role: owner / admin / member / viewer (read-only)
	Role string `json:"role"`
	// Membership status: pending / active / rejected (row kept for audit)
	Status string `json:"status"`
	// Reason submitted with the join request (nullable); meaningless on active rows
	RequestReason pgtype.Text `json:"request_reason"`
	// Reviewer user_id (set on approve or reject)
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
	// Review time (set on approve or reject)
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// Soft-delete timestamp; NULL = currently active member
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
