// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtimes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePairingToken = `-- name: ConsumePairingToken :one
update runtimes
set liveness                 = 'offline',
    hostname                 = $1,
    version                  = $2,
    config                   = coalesce(config, '{}'::jsonb) || $3::jsonb,
    pairing_token_hash       = null,
    pairing_token_expires_at = null,
    updated_at               = $4
where pairing_token_hash         = $5
  and liveness                   = 'pending_pairing'
  and pairing_token_expires_at   > $4
  and deleted_at                 is null
returning
  id::text          as id,
  workspace_id::text as workspace_id,
  type,
  name,
  liveness,
  provider,
  owner_user_id,
  hostname,
  version,
  config,
  created_at,
  updated_at
`

type ConsumePairingTokenParams struct {
	Hostname         string             `json:"hostname"`
	Version          string             `json:"version"`
	Config           []byte             `json:"config"`
	Now              pgtype.Timestamptz `json:"now"`
	PairingTokenHash pgtype.Text        `json:"pairing_token_hash"`
}

type ConsumePairingTokenRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Type        string             `json:"type"`
	Name        string             `json:"name"`
	Liveness    string             `json:"liveness"`
	Provider    string             `json:"provider"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Hostname    string             `json:"hostname"`
	Version     string             `json:"version"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Daemon-side: presented token hash matches and not expired ->
// promote pending_pairing -> offline (will go online on first
// heartbeat). Atomically clears the pairing token columns and
// writes the daemon-supplied hostname/version + X25519 public key
// (config jsonb). Returns the activated runtime so the daemon can
// learn its runtime_id + remember its credential.
//
// config jsonb is merged via concat (||) so admin-set keys set at
// create-pairing time survive the pair handshake — matches the
// SetRuntimeRunnerCredentialHash pattern in this file (round-1
// review F2).
func (q *Queries) ConsumePairingToken(ctx context.Context, arg ConsumePairingTokenParams) (ConsumePairingTokenRow, error) {
	row := q.db.QueryRow(ctx, consumePairingToken,
		arg.Hostname,
		arg.Version,
		arg.Config,
		arg.Now,
		arg.PairingTokenHash,
	)
	var i ConsumePairingTokenRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Liveness,
		&i.Provider,
		&i.OwnerUserID,
		&i.Hostname,
		&i.Version,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRuntimePairing = `-- name: CreateRuntimePairing :one

insert into runtimes(
  id, workspace_id, type, name, liveness, provider,
  owner_user_id, version, hostname,
  last_heartbeat_at,
  pairing_token_hash, pairing_token_expires_at,
  config, created_at, updated_at, deleted_at
)
values (
  $1::uuid, $2::uuid, $3, $4, 'pending_pairing', $5,
  $6::uuid, '', '',
  null,
  $7, $8,
  $9::jsonb, $10, $10, null
)
returning
  id::text                       as id,
  workspace_id::text             as workspace_id,
  type,
  name,
  liveness,
  provider,
  owner_user_id,
  version,
  hostname,
  last_heartbeat_at,
  pairing_token_expires_at,
  config,
  created_at,
  updated_at
`

type CreateRuntimePairingParams struct {
	ID                    pgtype.UUID        `json:"id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	Type                  string             `json:"type"`
	Name                  string             `json:"name"`
	Provider              string             `json:"provider"`
	OwnerUserID           pgtype.UUID        `json:"owner_user_id"`
	PairingTokenHash      pgtype.Text        `json:"pairing_token_hash"`
	PairingTokenExpiresAt pgtype.Timestamptz `json:"pairing_token_expires_at"`
	Config                []byte             `json:"config"`
	Now                   pgtype.Timestamptz `json:"now"`
}

type CreateRuntimePairingRow struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	Type                  string             `json:"type"`
	Name                  string             `json:"name"`
	Liveness              string             `json:"liveness"`
	Provider              string             `json:"provider"`
	OwnerUserID           pgtype.UUID        `json:"owner_user_id"`
	Version               string             `json:"version"`
	Hostname              string             `json:"hostname"`
	LastHeartbeatAt       pgtype.Timestamptz `json:"last_heartbeat_at"`
	PairingTokenExpiresAt pgtype.Timestamptz `json:"pairing_token_expires_at"`
	Config                []byte             `json:"config"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// runtimes.sql — runtime lifecycle and Agent Daemon pairing queries.
//
// Scope: SQL backing the runtimes table: admin lifecycle, daemon
// pairing, runtime credential heartbeat, and agent_daemon heartbeat
// capability persistence. Conventions follow the existing store.sql
// (uuid cast to text on the way out, jsonb cast for write-side params,
// @now/@id parameter naming).
// Admin UI calls this to register a new Agent Daemon runtime in
// pending_pairing state. The pairing token is generated server-side,
// hashed (sha256 hex) and stored here; the plaintext is returned to
// the caller exactly once and never persisted. Pairing window is
// short (typically 15min) so unused rows can be reaped without
// breaking active pairings.
func (q *Queries) CreateRuntimePairing(ctx context.Context, arg CreateRuntimePairingParams) (CreateRuntimePairingRow, error) {
	row := q.db.QueryRow(ctx, createRuntimePairing,
		arg.ID,
		arg.WorkspaceID,
		arg.Type,
		arg.Name,
		arg.Provider,
		arg.OwnerUserID,
		arg.PairingTokenHash,
		arg.PairingTokenExpiresAt,
		arg.Config,
		arg.Now,
	)
	var i CreateRuntimePairingRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Liveness,
		&i.Provider,
		&i.OwnerUserID,
		&i.Version,
		&i.Hostname,
		&i.LastHeartbeatAt,
		&i.PairingTokenExpiresAt,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntime = `-- name: GetRuntime :one
select
  id::text          as id,
  workspace_id::text as workspace_id,
  type,
  name,
  liveness,
  provider,
  owner_user_id,
  version,
  hostname,
  last_heartbeat_at,
  pairing_token_expires_at,
  config,
  created_at,
  updated_at
from runtimes
where id         = $1::uuid
  and deleted_at is null
`

type GetRuntimeRow struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	Type                  string             `json:"type"`
	Name                  string             `json:"name"`
	Liveness              string             `json:"liveness"`
	Provider              string             `json:"provider"`
	OwnerUserID           pgtype.UUID        `json:"owner_user_id"`
	Version               string             `json:"version"`
	Hostname              string             `json:"hostname"`
	LastHeartbeatAt       pgtype.Timestamptz `json:"last_heartbeat_at"`
	PairingTokenExpiresAt pgtype.Timestamptz `json:"pairing_token_expires_at"`
	Config                []byte             `json:"config"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Single runtime fetch (admin detail page + runner self-query).
// Includes deleted=false guard so soft-deleted runtimes are
// invisible to API surface; bypass via internal callers if ever
// needed (not in MVP).
func (q *Queries) GetRuntime(ctx context.Context, id pgtype.UUID) (GetRuntimeRow, error) {
	row := q.db.QueryRow(ctx, getRuntime, id)
	var i GetRuntimeRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Liveness,
		&i.Provider,
		&i.OwnerUserID,
		&i.Version,
		&i.Hostname,
		&i.LastHeartbeatAt,
		&i.PairingTokenExpiresAt,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeByCredentialHash = `-- name: GetRuntimeByCredentialHash :one
select
  id::text          as id,
  workspace_id::text as workspace_id,
  type,
  name,
  liveness,
  provider,
  owner_user_id,
  version,
  hostname,
  last_heartbeat_at,
  pairing_token_expires_at,
  config,
  created_at,
  updated_at
from runtimes
where config->>'runner_credential_hash' = $1::text
  and deleted_at                         is null
limit 1
`

type GetRuntimeByCredentialHashRow struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	Type                  string             `json:"type"`
	Name                  string             `json:"name"`
	Liveness              string             `json:"liveness"`
	Provider              string             `json:"provider"`
	OwnerUserID           pgtype.UUID        `json:"owner_user_id"`
	Version               string             `json:"version"`
	Hostname              string             `json:"hostname"`
	LastHeartbeatAt       pgtype.Timestamptz `json:"last_heartbeat_at"`
	PairingTokenExpiresAt pgtype.Timestamptz `json:"pairing_token_expires_at"`
	Config                []byte             `json:"config"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Bearer-only lookup for the runner_credential middleware. Resolves
// a long-lived runtime credential (sha256 hex) to its owning runtime
// without a URL/header-supplied runtime id — the daemon CLI's only
// credential dimension is the bearer.
//
// Filters mirror the existing bearer auth (deleted=false) so a leaked
// credential cannot resurrect a removed sandbox. Sequential scan today
// (no functional index on config->>'runner_credential_hash'); MVP scale
// of low-hundreds of active runtimes per workspace makes it cheap.
// Promote to a CREATE INDEX … ((config->>'runner_credential_hash'))
// when call volume warrants it.
func (q *Queries) GetRuntimeByCredentialHash(ctx context.Context, credentialHash string) (GetRuntimeByCredentialHashRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeByCredentialHash, credentialHash)
	var i GetRuntimeByCredentialHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Liveness,
		&i.Provider,
		&i.OwnerUserID,
		&i.Version,
		&i.Hostname,
		&i.LastHeartbeatAt,
		&i.PairingTokenExpiresAt,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRuntimesByWorkspace = `-- name: ListRuntimesByWorkspace :many
select
  id::text          as id,
  workspace_id::text as workspace_id,
  type,
  name,
  liveness,
  provider,
  owner_user_id,
  version,
  hostname,
  last_heartbeat_at,
  pairing_token_expires_at,
  config,
  created_at,
  updated_at
from runtimes
where workspace_id = $1::uuid
  and deleted_at   is null
  and ($2 = '' or type::text = $2)
order by created_at desc
limit $3::int
`

type ListRuntimesByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Type        interface{} `json:"type"`
	LimitN      int32       `json:"limit_n"`
}

type ListRuntimesByWorkspaceRow struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	Type                  string             `json:"type"`
	Name                  string             `json:"name"`
	Liveness              string             `json:"liveness"`
	Provider              string             `json:"provider"`
	OwnerUserID           pgtype.UUID        `json:"owner_user_id"`
	Version               string             `json:"version"`
	Hostname              string             `json:"hostname"`
	LastHeartbeatAt       pgtype.Timestamptz `json:"last_heartbeat_at"`
	PairingTokenExpiresAt pgtype.Timestamptz `json:"pairing_token_expires_at"`
	Config                []byte             `json:"config"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Admin UI Runtime page list. Filters by optional type so the
// per-tab views (Agent Daemon / Sandbox / External) reuse one query.
// Empty string in @type means "all types".
func (q *Queries) ListRuntimesByWorkspace(ctx context.Context, arg ListRuntimesByWorkspaceParams) ([]ListRuntimesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listRuntimesByWorkspace, arg.WorkspaceID, arg.Type, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimesByWorkspaceRow{}
	for rows.Next() {
		var i ListRuntimesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Name,
			&i.Liveness,
			&i.Provider,
			&i.OwnerUserID,
			&i.Version,
			&i.Hostname,
			&i.LastHeartbeatAt,
			&i.PairingTokenExpiresAt,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRuntimeOffline = `-- name: MarkRuntimeOffline :exec
UPDATE runtimes
SET liveness   = 'offline',
    updated_at = $1
WHERE id         = $2::uuid
  AND liveness   = 'online'
  AND deleted_at IS NULL
`

type MarkRuntimeOfflineParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

// Instant offline marking on WebSocket session close. Idempotent: only
// touches rows that are currently online.
func (q *Queries) MarkRuntimeOffline(ctx context.Context, arg MarkRuntimeOfflineParams) error {
	_, err := q.db.Exec(ctx, markRuntimeOffline, arg.Now, arg.ID)
	return err
}

const patchRuntime = `-- name: PatchRuntime :one
update runtimes
set name            = case when $1::text          = '' then name            else $1 end,
    updated_at      = $2
where id         = $3::uuid
  and deleted_at is null
returning
  id::text          as id,
  workspace_id::text as workspace_id,
  type,
  name,
  liveness,
  provider,
  owner_user_id,
  version,
  hostname,
  last_heartbeat_at,
  pairing_token_expires_at,
  config,
  created_at,
  updated_at
`

type PatchRuntimeParams struct {
	NewName string             `json:"new_name"`
	Now     pgtype.Timestamptz `json:"now"`
	ID      pgtype.UUID        `json:"id"`
}

type PatchRuntimeRow struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	Type                  string             `json:"type"`
	Name                  string             `json:"name"`
	Liveness              string             `json:"liveness"`
	Provider              string             `json:"provider"`
	OwnerUserID           pgtype.UUID        `json:"owner_user_id"`
	Version               string             `json:"version"`
	Hostname              string             `json:"hostname"`
	LastHeartbeatAt       pgtype.Timestamptz `json:"last_heartbeat_at"`
	PairingTokenExpiresAt pgtype.Timestamptz `json:"pairing_token_expires_at"`
	Config                []byte             `json:"config"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Admin PATCH: rename. Empty string means "do not change" (preserves
// the current value).
func (q *Queries) PatchRuntime(ctx context.Context, arg PatchRuntimeParams) (PatchRuntimeRow, error) {
	row := q.db.QueryRow(ctx, patchRuntime, arg.NewName, arg.Now, arg.ID)
	var i PatchRuntimeRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Liveness,
		&i.Provider,
		&i.OwnerUserID,
		&i.Version,
		&i.Hostname,
		&i.LastHeartbeatAt,
		&i.PairingTokenExpiresAt,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRuntimeRunnerCredentialHash = `-- name: SetRuntimeRunnerCredentialHash :exec
update runtimes
set config     = coalesce(config, '{}'::jsonb) || jsonb_build_object('runner_credential_hash', $1::text),
    updated_at = $2
where id         = $3::uuid
  and deleted_at is null
`

type SetRuntimeRunnerCredentialHashParams struct {
	Hash string             `json:"hash"`
	Now  pgtype.Timestamptz `json:"now"`
	ID   pgtype.UUID        `json:"id"`
}

// Pair handshake follow-up: after ConsumePairingToken promotes the
// row to offline + writes runner_public_key, we mint a long-lived
// runtime bearer credential and stash its hash under
// config.runner_credential_hash. jsonb-concat preserves runner_public_key
// + any other admin-set keys; written as one round trip so the daemon
// never sees a partially-paired row.
func (q *Queries) SetRuntimeRunnerCredentialHash(ctx context.Context, arg SetRuntimeRunnerCredentialHashParams) error {
	_, err := q.db.Exec(ctx, setRuntimeRunnerCredentialHash, arg.Hash, arg.Now, arg.ID)
	return err
}

const softDeleteRuntime = `-- name: SoftDeleteRuntime :exec
update runtimes
set deleted_at  = $1,
    updated_at  = $1
where id         = $2::uuid
  and deleted_at is null
`

type SoftDeleteRuntimeParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

// Admin "remove". Soft-delete only; agent_runs.runtime_id stays
// as the historical FK (the FK is ON DELETE SET NULL, but soft
// delete leaves it intact so Run Detail can still display "ran
// on alice-laptop (deleted)").
func (q *Queries) SoftDeleteRuntime(ctx context.Context, arg SoftDeleteRuntimeParams) error {
	_, err := q.db.Exec(ctx, softDeleteRuntime, arg.Now, arg.ID)
	return err
}

const softDeleteRuntimeByWorkspaceName = `-- name: SoftDeleteRuntimeByWorkspaceName :exec
update runtimes
set deleted_at  = $1,
    updated_at  = $1
where workspace_id = $2::uuid
  and name         = $3
  and deleted_at   is null
`

type SoftDeleteRuntimeByWorkspaceNameParams struct {
	Now         pgtype.Timestamptz `json:"now"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
}

// Retire any active runtime with the given workspace+name so a
// replacement can be created without hitting the
// uk_runtimes_workspace_name_active unique constraint.
func (q *Queries) SoftDeleteRuntimeByWorkspaceName(ctx context.Context, arg SoftDeleteRuntimeByWorkspaceNameParams) error {
	_, err := q.db.Exec(ctx, softDeleteRuntimeByWorkspaceName, arg.Now, arg.WorkspaceID, arg.Name)
	return err
}

const sweepStaleRuntimesToOffline = `-- name: SweepStaleRuntimesToOffline :execrows
update runtimes
set liveness   = 'offline',
    updated_at = $1
where deleted_at        is null
  and liveness          = 'online'
  and last_heartbeat_at < $2
`

type SweepStaleRuntimesToOfflineParams struct {
	Now    pgtype.Timestamptz `json:"now"`
	Cutoff pgtype.Timestamptz `json:"cutoff"`
}

// Background sweeper: runtimes whose last_heartbeat_at is older
// than the cutoff get demoted online -> offline. Operator picks
// the cutoff (typically 3-5x the runner heartbeat interval, e.g.
// runner ticks every 10s => cutoff 30-60s). Returns row count
// for sweep telemetry.
func (q *Queries) SweepStaleRuntimesToOffline(ctx context.Context, arg SweepStaleRuntimesToOfflineParams) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStaleRuntimesToOffline, arg.Now, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAgentDaemonHeartbeat = `-- name: TouchAgentDaemonHeartbeat :one
update runtimes
set last_heartbeat_at = $1,
    liveness          = 'online',
    version           = case when $2::text = '' then version else $2 end,
    config            = coalesce(config, '{}'::jsonb) || jsonb_build_object(
      'supported_agent_kinds', $3::jsonb,
      'supported_agent_kind_names', $4::jsonb,
      'daemon_capabilities', $5::jsonb,
      'agent_daemon_active_requests', $6::int,
      'agent_daemon_heartbeat_ts', $7::bigint
    ),
    updated_at        = $1
where id          = $8::uuid
  and deleted_at  is null
  and type        = 'agent_daemon'
  and liveness    in ('offline', 'online', 'error')
returning
  id::text       as id,
  liveness,
  last_heartbeat_at
`

type TouchAgentDaemonHeartbeatParams struct {
	Now                     pgtype.Timestamptz `json:"now"`
	DaemonVersion           string             `json:"daemon_version"`
	SupportedAgentKinds     []byte             `json:"supported_agent_kinds"`
	SupportedAgentKindNames []byte             `json:"supported_agent_kind_names"`
	DaemonCapabilities      []byte             `json:"daemon_capabilities"`
	ActiveRequests          int32              `json:"active_requests"`
	HeartbeatTs             int64              `json:"heartbeat_ts"`
	ID                      pgtype.UUID        `json:"id"`
}

type TouchAgentDaemonHeartbeatRow struct {
	ID              string             `json:"id"`
	Liveness        string             `json:"liveness"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
}

// WebSocket agent_daemon heartbeat: bump liveness and persist the
// daemon-advertised agent_kind capability snapshot. This keeps the
// Runtime page and DevicePicker on the same source of truth without a
// new table/migration; agent_daemon is already the runtime type that
// owns these config keys.
func (q *Queries) TouchAgentDaemonHeartbeat(ctx context.Context, arg TouchAgentDaemonHeartbeatParams) (TouchAgentDaemonHeartbeatRow, error) {
	row := q.db.QueryRow(ctx, touchAgentDaemonHeartbeat,
		arg.Now,
		arg.DaemonVersion,
		arg.SupportedAgentKinds,
		arg.SupportedAgentKindNames,
		arg.DaemonCapabilities,
		arg.ActiveRequests,
		arg.HeartbeatTs,
		arg.ID,
	)
	var i TouchAgentDaemonHeartbeatRow
	err := row.Scan(&i.ID, &i.Liveness, &i.LastHeartbeatAt)
	return i, err
}

const touchRuntimeHeartbeat = `-- name: TouchRuntimeHeartbeat :one
update runtimes
set last_heartbeat_at = $1,
    liveness          = 'online',
    updated_at        = $1
where id          = $2::uuid
  and deleted_at  is null
  and liveness    in ('offline', 'online', 'error')
returning
  id::text       as id,
  liveness,
  last_heartbeat_at
`

type TouchRuntimeHeartbeatParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

type TouchRuntimeHeartbeatRow struct {
	ID              string             `json:"id"`
	Liveness        string             `json:"liveness"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
}

// Bumps last_heartbeat_at and transitions the runtime to 'online'
// if it was offline/error. Soft-deleted runtimes are not promoted.
// Returns the new liveness.
func (q *Queries) TouchRuntimeHeartbeat(ctx context.Context, arg TouchRuntimeHeartbeatParams) (TouchRuntimeHeartbeatRow, error) {
	row := q.db.QueryRow(ctx, touchRuntimeHeartbeat, arg.Now, arg.ID)
	var i TouchRuntimeHeartbeatRow
	err := row.Scan(&i.ID, &i.Liveness, &i.LastHeartbeatAt)
	return i, err
}
