// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spec_fragments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSpecFragment = `-- name: GetSpecFragment :one
select
  id::text           as id,
  workspace_id::text as workspace_id,
  title,
  body,
  tags,
  source,
  created_by,
  agent_actor,
  created_at,
  updated_at
from spec_fragments
where id         = $1::uuid
  and deleted_at is null
`

type GetSpecFragmentRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Tags        []string           `json:"tags"`
	Source      string             `json:"source"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AgentActor  string             `json:"agent_actor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Single fragment fetch (UI detail page + audit replay). Filters
// soft-deleted rows; admin/forensic reads should use a separate
// query that drops the deleted_at guard if ever needed.
func (q *Queries) GetSpecFragment(ctx context.Context, id pgtype.UUID) (GetSpecFragmentRow, error) {
	row := q.db.QueryRow(ctx, getSpecFragment, id)
	var i GetSpecFragmentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Source,
		&i.CreatedBy,
		&i.AgentActor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSpecFragment = `-- name: InsertSpecFragment :one

insert into spec_fragments (
  id, workspace_id, title, body, tags,
  source, created_by, agent_actor,
  created_at, updated_at
)
values (
  $1::uuid, $2::uuid, $3, $4, $5::text[],
  $6, $7::uuid, $8,
  $9, $9
)
returning
  id::text           as id,
  workspace_id::text as workspace_id,
  title,
  body,
  tags,
  source,
  created_by,
  agent_actor,
  created_at,
  updated_at
`

type InsertSpecFragmentParams struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Tags        []string           `json:"tags"`
	Source      string             `json:"source"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AgentActor  string             `json:"agent_actor"`
	Now         pgtype.Timestamptz `json:"now"`
}

type InsertSpecFragmentRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Tags        []string           `json:"tags"`
	Source      string             `json:"source"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AgentActor  string             `json:"agent_actor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// spec_fragments.sql — workspace-scoped spec fragments backing the
// spec & memory injection feature (see docs/spec-memory-module.md).
//
// Conventions follow audit_records.sql / runtimes.sql in this dir:
//   - application-layer @id::uuid + @now::timestamptz (no DB defaults
//     for id/created_at/updated_at per migration 000004)
//   - @param::type casts on every parameter for sqlc pgx/v5 codegen
//   - empty-string / empty-array sentinels mean "skip this filter"
//     so list endpoints can reuse one query for unfiltered + filtered
//     views without proliferating query variants
//   - source / created_by / agent_actor write-source triple is
//     validated in the Go service layer (specmemory.Source enum);
//     SQL just stores whatever the caller passes
//
// Soft delete is the only delete: idx_spec_fragments_workspace_active
// is partial WHERE deleted_at IS NULL so reads stay fast as the table
// accumulates tombstones. List queries always filter `deleted_at is null`.
// Single insert path for both UI ("manual"/"import") and agent
// ("agent") writes. Caller is responsible for setting created_by
// (UI: signed-in user; agent: pgtype.UUID{Valid:false}) and
// agent_actor (UI: ”; agent: 'connector:agentID').
func (q *Queries) InsertSpecFragment(ctx context.Context, arg InsertSpecFragmentParams) (InsertSpecFragmentRow, error) {
	row := q.db.QueryRow(ctx, insertSpecFragment,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.Source,
		arg.CreatedBy,
		arg.AgentActor,
		arg.Now,
	)
	var i InsertSpecFragmentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Source,
		&i.CreatedBy,
		&i.AgentActor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceSpecFragments = `-- name: ListWorkspaceSpecFragments :many
select
  id::text           as id,
  workspace_id::text as workspace_id,
  title,
  body,
  tags,
  source,
  created_by,
  agent_actor,
  created_at,
  updated_at
from spec_fragments
where workspace_id = $1::uuid
  and deleted_at   is null
  and ($2::text = '' or source = $2::text)
  and (cardinality($3::text[]) = 0
       or tags && $3::text[])
order by updated_at desc, id desc
limit $4::int
`

type ListWorkspaceSpecFragmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Source      string      `json:"source"`
	TagFilter   []string    `json:"tag_filter"`
	ItemLimit   int32       `json:"item_limit"`
}

type ListWorkspaceSpecFragmentsRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Tags        []string           `json:"tags"`
	Source      string             `json:"source"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AgentActor  string             `json:"agent_actor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Primary list query for both UI (Spec tab) and SessionStart
// injection snapshot. Filters:
//   - @source::text — empty string skips; otherwise exact match
//     (e.g. only "agent"-authored fragments)
//   - @tag_filter::text[] — empty array skips; otherwise overlap
//     (tags && filter), backed by idx_spec_fragments_tags_active
//
// Order by updated_at desc so the freshest fragments dominate the
// injection budget when callers cap with @item_limit.
func (q *Queries) ListWorkspaceSpecFragments(ctx context.Context, arg ListWorkspaceSpecFragmentsParams) ([]ListWorkspaceSpecFragmentsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceSpecFragments,
		arg.WorkspaceID,
		arg.Source,
		arg.TagFilter,
		arg.ItemLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceSpecFragmentsRow{}
	for rows.Next() {
		var i ListWorkspaceSpecFragmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Source,
			&i.CreatedBy,
			&i.AgentActor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceSpecFragmentsSince = `-- name: ListWorkspaceSpecFragmentsSince :many
select
  id::text           as id,
  workspace_id::text as workspace_id,
  title,
  body,
  tags,
  source,
  created_by,
  agent_actor,
  created_at,
  updated_at
from spec_fragments
where workspace_id = $1::uuid
  and deleted_at   is null
  and updated_at   > $2::timestamptz
order by updated_at asc, id asc
limit $3::int
`

type ListWorkspaceSpecFragmentsSinceParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Since       pgtype.Timestamptz `json:"since"`
	ItemLimit   int32              `json:"item_limit"`
}

type ListWorkspaceSpecFragmentsSinceRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Tags        []string           `json:"tags"`
	Source      string             `json:"source"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AgentActor  string             `json:"agent_actor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Per-turn incremental injection cursor. Returns fragments whose
// updated_at is strictly greater than the cursor — covers both new
// inserts and edits to existing rows. Soft-deleted rows are excluded
// here; deletions are surfaced via a separate query if the per-turn
// hook ever needs to retract a previously-injected fragment.
func (q *Queries) ListWorkspaceSpecFragmentsSince(ctx context.Context, arg ListWorkspaceSpecFragmentsSinceParams) ([]ListWorkspaceSpecFragmentsSinceRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceSpecFragmentsSince, arg.WorkspaceID, arg.Since, arg.ItemLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceSpecFragmentsSinceRow{}
	for rows.Next() {
		var i ListWorkspaceSpecFragmentsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Source,
			&i.CreatedBy,
			&i.AgentActor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSpecFragment = `-- name: SoftDeleteSpecFragment :exec
update spec_fragments
set deleted_at = $1,
    updated_at = $1
where id         = $2::uuid
  and deleted_at is null
`

type SoftDeleteSpecFragmentParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

// Tombstone the fragment. Idempotent on already-deleted rows (no
// match -> no update). Hard delete is intentionally absent: audit
// replay needs the body around to render historical injections.
func (q *Queries) SoftDeleteSpecFragment(ctx context.Context, arg SoftDeleteSpecFragmentParams) error {
	_, err := q.db.Exec(ctx, softDeleteSpecFragment, arg.Now, arg.ID)
	return err
}

const updateSpecFragment = `-- name: UpdateSpecFragment :one
update spec_fragments
set title      = $1,
    body       = $2,
    tags       = $3::text[],
    updated_at = $4
where id         = $5::uuid
  and deleted_at is null
returning
  id::text           as id,
  workspace_id::text as workspace_id,
  title,
  body,
  tags,
  source,
  created_by,
  agent_actor,
  created_at,
  updated_at
`

type UpdateSpecFragmentParams struct {
	Title string             `json:"title"`
	Body  string             `json:"body"`
	Tags  []string           `json:"tags"`
	Now   pgtype.Timestamptz `json:"now"`
	ID    pgtype.UUID        `json:"id"`
}

type UpdateSpecFragmentRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Tags        []string           `json:"tags"`
	Source      string             `json:"source"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AgentActor  string             `json:"agent_actor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Full-replace update (UI edits + agent rewrites). Caller does
// read-modify-write; this query is a dumb writer that bumps
// updated_at. Soft-deleted rows are immutable (deleted_at guard).
// We deliberately do NOT let updates change source/created_by/
// agent_actor — provenance is fixed at insert time; subsequent
// edits inherit the original triple.
func (q *Queries) UpdateSpecFragment(ctx context.Context, arg UpdateSpecFragmentParams) (UpdateSpecFragmentRow, error) {
	row := q.db.QueryRow(ctx, updateSpecFragment,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.Now,
		arg.ID,
	)
	var i UpdateSpecFragmentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Source,
		&i.CreatedBy,
		&i.AgentActor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
